const railTop = 96;
const railWidth = 340;
const railGap = 60;
const measure = 760;
const shell = railWidth + railGap + measure;

const styles = {
  page: {
    width: '100%',
    alignSelf: 'center',
    boxSizing: 'border-box',
    px: { xs: 1, sm: 2, md: 3 },
    pt: { xs: 1, md: 2 },
    gap: { xs: 2.5, md: 4.5 },
    pb: { xs: 6, md: 10 },
  },

  cover: {
    position: 'relative',
    width: '100%',
    maxWidth: shell,
    mx: 'auto',
    aspectRatio: { xs: '16/9', sm: '16/3' },
    overflow: 'hidden',
    borderRadius: 0,
    bgcolor: '#F8F6F2',
  },

  header: {
    width: '100%',
    gap: { xs: 1.25, md: 1.5 },
    mb: { xs: 3, md: 4 },
  },
  byline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 1.25,
    fontSize: { xs: 12.5, md: 13.5 },
    color: '#8E8E93',
  },
  bylineAvatar: {
    width: 30,
    height: 30,
    flex: 'none',
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    bgcolor: '#F2EFEA',
    color: '#8A6A55',
    fontSize: 12,
    fontWeight: 700,
  },
  bylineName: {
    fontSize: 13.5,
    fontWeight: 600,
    color: '#3A3A3C',
  },
  eyebrow: {
    color: '#C1121F',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.14em',
    lineHeight: 1.2,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: { xs: 25, sm: 29, md: 33 },
    fontWeight: 600,
    color: '#1C1C1E',
    lineHeight: 1.18,
    letterSpacing: '-0.02em',
    textWrap: 'pretty',
  },
  excerpt: {
    maxWidth: measure,
    fontSize: { xs: 16, md: 19 },
    color: '#48484A',
    lineHeight: 1.65,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 1,
    fontSize: { xs: 12.5, md: 13.5 },
    color: '#8E8E93',
  },
  metaStrong: {
    fontSize: 'inherit',
    fontWeight: 600,
    color: '#3A3A3C',
  },
  metaText: {
    fontSize: 'inherit',
    color: 'inherit',
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: '50%',
    bgcolor: '#C7C7CC',
    flex: 'none',
  },
  shareLabel: {
    color: '#8E8E93',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },

  grid: {
    display: 'grid',
    alignItems: 'start',
    width: '100%',
    maxWidth: shell,
    mx: 'auto',
    columnGap: { lg: `${railGap}px` },
    gridTemplateColumns: {
      xs: 'minmax(0, 1fr)',
      lg: `minmax(0, ${measure}px) ${railWidth}px`,
    },
  },
  railRight: {
    display: { xs: 'none', lg: 'block' },
    position: 'sticky',
    top: railTop,
    maxHeight: `calc(100vh - ${railTop + 32}px)`,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    '&::-webkit-scrollbar': { width: 0 },
    scrollbarWidth: 'none',
  },
  contentColumn: {
    minWidth: 0,
  },

  sidebarBlock: {
    gap: 1.25,
    pb: 3,
    '&:first-of-type': { mt: 0 },
  },
  sidebarTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: '#1C1C1E',
    pb: 1.25,
    borderBottom: '1px solid #E5E5EA',
  },
  // Arama bloğunda ayrac yok: gri input zaten kendi sinirini ciziyor.
  sidebarTitlePlain: {
    fontSize: 15,
    fontWeight: 700,
    color: '#1C1C1E',
  },
  sidebarSearch: {
    width: '100%',
    boxSizing: 'border-box',
    px: 1.5,
    py: 1.25,
    fontSize: 13,
    fontFamily: 'inherit',
    color: '#1C1C1E',
    bgcolor: '#F2F2F7',
    border: 'none',
    borderRadius: 0,
    outline: 'none',
    '&::placeholder': { color: '#AEAEB2' },
    '&:focus': { bgcolor: '#EBEBF0' },
  },
  sidebarItem: {
    display: 'block',
    py: 1.5,
    textDecoration: 'none',
    borderBottom: '1px solid #E5E5EA',
    '&:last-of-type': { borderBottom: 'none' },
    '&:hover h3': { color: '#C1121F' },
  },
  sidebarItemTitle: {
    m: 0,
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 1.5,
    color: '#3A3A3C',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    transition: 'color 0.15s ease',
  },
  sidebarItemDate: {
    mt: 0.75,
    fontSize: 11.5,
    color: '#AEAEB2',
  },
  sidebarEmpty: {
    py: 1.5,
    fontSize: 12.5,
    color: '#AEAEB2',
  },

  related: {
    width: '100%',
    maxWidth: shell,
    mx: 'auto',
    mt: { xs: 4, md: 7 },
    pt: { xs: 4, md: 6 },
    borderTop: '1px solid #E5E5EA',
    gap: { xs: 2.5, md: 4 },
  },
  relatedTitle: {
    textAlign: 'center',
    fontSize: { xs: 22, md: 28 },
    fontWeight: 700,
    color: '#1C1C1E',
    letterSpacing: '-0.02em',
  },
  relatedGrid: {
    display: 'grid',
    gap: { xs: 2.5, md: 3 },
    gridTemplateColumns: {
      xs: 'minmax(0, 1fr)',
      sm: 'repeat(2, minmax(0, 1fr))',
      md: 'repeat(3, minmax(0, 1fr))',
    },
  },

  mobileToc: {
    display: { xs: 'block', lg: 'none' },
    bgcolor: '#FAFAFA',
    border: '1px solid #E5E5EA',
    borderRadius: 2.5,
    px: { xs: 2, md: 2.5 },
    py: { xs: 1.75, md: 2 },
    mb: { xs: 3.5, md: 4.5 },
    '& summary': {
      listStyle: 'none',
      cursor: 'pointer',
      fontSize: 13,
      fontWeight: 700,
      letterSpacing: '0.08em',
      textTransform: 'uppercase',
      color: '#1C1C1E',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    '& summary::-webkit-details-marker': { display: 'none' },
    '& summary small': {
      ml: 'auto',
      mr: 1.5,
      color: '#8E8E93',
      fontSize: 11.5,
      fontWeight: 500,
      letterSpacing: 0,
      textTransform: 'none',
    },
    '& summary::after': { content: '"+"', color: '#8E8E93', fontSize: 18, fontWeight: 400 },
    '&[open] summary::after': { content: '"–"' },
    '& ol': {
      m: '16px 0 4px',
      pl: 2.75,
      fontSize: 13.5,
      color: '#3A3A3C',
      '& li': { mb: 0.9, breakInside: 'avoid' },
      '& a': { color: 'inherit', textDecoration: 'none' },
      '& a:hover': { color: '#C1121F' },
    },
  },

  productCard: {
    border: '1px solid #E5E5EA',
    borderRadius: 2,
    p: 2,
    gap: 1.5,
  },
  productList: {
    gap: 1.5,
  },
  productLink: {
    textDecoration: 'none',
    color: 'inherit',
    display: 'block',
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.25,
    borderRadius: 1.5,
    transition: 'background-color 0.15s ease',
    '&:hover': { bgcolor: '#F5F5F7' },
  },
  productThumb: {
    position: 'relative',
    flex: 'none',
    width: 64,
    height: 64,
    borderRadius: 1.5,
    overflow: 'hidden',
    bgcolor: '#F5F5F7',
  },
  productImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    display: 'block',
  },
  productBadge: {
    position: 'absolute',
    left: 3,
    bottom: 3,
    px: 0.5,
    borderRadius: '4px',
    bgcolor: '#C1121F',
    color: '#FFF',
    fontSize: 10,
    fontWeight: 700,
    lineHeight: '15px',
  },
  productInfo: {
    minWidth: 0,
    gap: 0.25,
  },
  productBrand: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#8E8E93',
  },
  productName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#1C1C1E',
    lineHeight: 1.35,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  productPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 0.75,
    mt: 0.25,
  },
  productPrice: {
    fontSize: 13.5,
    fontWeight: 700,
    color: '#1C1C1E',
  },
  productOldPrice: {
    fontSize: 11.5,
    color: '#8E8E93',
    textDecoration: 'line-through',
  },
  productAllLink: {
    fontSize: 12.5,
    fontWeight: 600,
    color: '#C1121F',
    textDecoration: 'none',
    '&:hover': { textDecoration: 'underline' },
  },

  sideCard: {
    border: '1px solid #E5E5EA',
    borderRadius: 2,
    p: 2,
    gap: 1,
  },
  sideLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#8E8E93',
  },
  sideTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#1C1C1E',
  },
  sideText: {
    fontSize: 13,
    color: '#6E6E73',
    lineHeight: 1.55,
  },

  authorCard: {
    alignItems: 'flex-start',
    gap: 2,
    mt: { xs: 5, md: 7 },
    pt: { xs: 3, md: 3.5 },
    borderTop: '1px solid #E5E5EA',
  },
  authorMark: {
    display: 'grid',
    placeItems: 'center',
    width: 48,
    height: 48,
    flex: '0 0 48px',
    borderRadius: '50%',
    bgcolor: '#1C1C1E',
    color: '#FFF',
    fontSize: 18,
    fontWeight: 800,
  },
  authorBody: {
    maxWidth: 580,
    gap: 0.35,
  },
  authorLabel: {
    color: '#8E8E93',
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: '0.11em',
    textTransform: 'uppercase',
  },
  authorTitle: {
    color: '#1C1C1E',
    fontSize: 15,
    fontWeight: 700,
  },
  authorText: {
    color: '#6E6E73',
    fontSize: { xs: 13.5, md: 14 },
    lineHeight: 1.6,
  },
  footerShare: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 1,
    mt: 3,
    pl: { xs: 0, sm: 8 },
  },

  notFound: {
    py: 12,
    gap: 1.5,
  },
  notFoundTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#1C1C1E',
  },
  notFoundSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
  },

  article: {
    color: '#3A3A3C',
    fontSize: { xs: 16, md: 19 },
    lineHeight: 1.7,
    letterSpacing: '0.005em',
    maxWidth: '100%',

    // Ilk basligin mt'si iki kolonu kaydiriyordu; sag rail ile ayni satirda baslasin.
    '& > *:first-of-type': { mt: 0 },

    '& h1': {
      fontSize: { xs: 24, md: 30 },
      fontWeight: 800,
      color: '#1C1C1E',
      mt: 5,
      mb: 2,
      lineHeight: 1.25,
      scrollMarginTop: `${railTop}px`,
    },
    '& h2': {
      fontSize: { xs: 22, md: 28 },
      fontWeight: 700,
      color: '#1C1C1E',
      mt: 5,
      mb: 1.5,
      lineHeight: 1.3,
      letterSpacing: '-0.01em',
      scrollMarginTop: `${railTop}px`,
    },
    '& h3': {
      fontSize: { xs: 18, md: 21 },
      fontWeight: 700,
      color: '#1C1C1E',
      mt: 3.5,
      mb: 1,
      lineHeight: 1.35,
      scrollMarginTop: `${railTop}px`,
    },
    '& h4, & h5, & h6': {
      fontSize: { xs: 16, md: 18 },
      fontWeight: 600,
      color: '#1C1C1E',
      mt: 2.5,
      mb: 1,
    },
    '& p': {
      mb: 2,
      '&:last-child': { mb: 0 },
    },
    '& a': {
      color: '#1C1C1E',
      fontWeight: 600,
      textDecorationColor: '#C1121F',
      textUnderlineOffset: '3px',
      transition: 'color 0.2s ease',
      '&:hover': { color: '#C1121F' },
    },
    '& img': {
      maxWidth: '100%',
      height: 'auto',
      borderRadius: '8px',
      my: 3,
    },
    '& blockquote': {
      borderLeft: '3px solid #C1121F',
      borderTop: '1px solid #E5E5EA',
      borderRight: '1px solid #E5E5EA',
      borderBottom: '1px solid #E5E5EA',
      borderRadius: '0 10px 10px 0',
      bgcolor: '#FCFCFD',
      p: { xs: 2, md: 2.5 },
      ml: 0,
      my: 3,
      color: '#2C2C2E',
      fontSize: { xs: 15, md: 16.5 },
      lineHeight: 1.7,
      '& p:last-child': { mb: 0 },
    },
    '& ul, & ol': {
      pl: 3,
      mb: 2,
      '& li': { mb: 0.75 },
    },
    '& pre': {
      bgcolor: '#F5F5F7',
      borderRadius: '8px',
      p: 2.5,
      overflow: 'auto',
      my: 3,
      fontSize: 14,
    },
    '& code': {
      bgcolor: '#F5F5F7',
      px: 0.75,
      py: 0.25,
      borderRadius: '4px',
      fontSize: '0.9em',
    },
    // prepareArticle her tabloyu bu sarmalayıcıya alıyor
    '& .article-table': {
      my: 3,
      overflowX: 'auto',
      WebkitOverflowScrolling: 'touch',
    },
    '& .article-table table': { my: 0, minWidth: 420 },
    '& table': {
      width: '100%',
      borderCollapse: 'collapse',
      my: 3,
      fontVariantNumeric: 'tabular-nums',
      '& th, & td': {
        border: '1px solid #E5E5EA',
        px: 2,
        py: 1.25,
        textAlign: 'left',
        verticalAlign: 'top',
        fontSize: 14,
      },
      '& th': {
        bgcolor: '#F5F5F7',
        fontWeight: 600,
        color: '#1C1C1E',
        fontSize: 13,
      },
    },
    '& strong, & b': {
      fontWeight: 700,
      color: '#1C1C1E',
    },
  },
};

export default styles;
