import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  container: {
    position: 'fixed',
    left: { xs: 0, sm: 16, md: 20 },
    right: { xs: 0, sm: 'auto' },
    bottom: { xs: 12, sm: 16 },
    zIndex: 1400,
    pointerEvents: 'none',
    px: { xs: 1.5, sm: 0 },
  },
  bar: {
    pointerEvents: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    width: { xs: '100%', sm: 390 },
    maxWidth: { xs: '100%', sm: 390 },
    mx: { xs: 'auto', sm: 0 },
    px: { xs: 1.5, sm: 2 },
    py: { xs: 1.5, sm: 1.75 },
    borderRadius: 1,
    background: palette.white.main,
    boxShadow: '0px 12px 32px rgba(28, 28, 30, 0.1)',
    border: `1px solid ${palette.gray[100]}`,
  },
  content: {
    width: '100%',
    gap: 0.9,
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
  },
  eyebrowRow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    color: palette.text.mediumLight,
  },
  eyebrow: {
    color: palette.text.mediumLight,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1,
  },
  heading: {
    color: palette.text.main,
    fontSize: 14,
    lineHeight: 1.45,
    fontWeight: 500,
    '& strong': {
      fontWeight: 700,
    },
  },
  policyLink: {
    display: 'inline-flex',
    color: palette.text.main,
    opacity: 1,
    fontSize: 12,
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 1.25,
    width: '100%',
    mt: 0.4,
    flexDirection: 'row',
    flexWrap: 'nowrap',
  },
  dismissButton: {
    width: 28,
    height: 28,
    minWidth: 28,
    borderRadius: '50%',
    color: palette.text.mediumLight,
    backgroundColor: 'transparent',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.18s ease',
    '&:hover': {
      color: palette.text.main,
      backgroundColor: palette.bg.dark,
    },
  },
  customizeButton: {
    minWidth: 'auto',
    height: 36,
    px: 2.5,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  acceptButton: {
    minWidth: 132,
    height: 36,
    borderRadius: 1.5,
    px: 2.5,
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '0.02em',
  },
  triggerButton: {
    pointerEvents: 'auto',
    width: 52,
    height: 52,
    minWidth: 52,
    borderRadius: '50%',
    background: palette.white.main,
    color: palette.gray[500],
    border: `1px solid ${palette.gray[100]}`,
    boxShadow: '0px 10px 24px rgba(28, 28, 30, 0.12)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'transform 0.18s ease, box-shadow 0.18s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0px 14px 28px rgba(28, 28, 30, 0.16)',
    },
  },
}));

export default useStyles;
