export const uzbekistanCities = [
  { value: 'tashkent' },
  { value: 'samarkand' },
  { value: 'andijan' },
  { value: 'bukhara' },
  { value: 'chirchiq' },
  { value: 'fergana' },
  { value: 'gulistan' },
  { value: 'jizzakh' },
  { value: 'karshi' },
  { value: 'khiva' },
  { value: 'kokand' },
  { value: 'margilan' },
  { value: 'namangan' },
  { value: 'navoi' },
  { value: 'nukus' },
  { value: 'termez' },
];
