const phoneCodes = [
  {
    name: 'Uzbekistan',
    code: 'UZ',
    phoneCode: '+998',
    localName: 'Oʻzbekiston',
    turkishName: 'Özbekistan',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    phoneCode: '+234',
    localName: 'Nigeria',
    turkishName: 'Nijerya',
  },
  {
    name: 'Turkiye',
    code: 'TR',
    phoneCode: '+90',
    localName: 'Türkiye',
    turkishName: 'Türkiye',
  },
  {
    name: 'Afghanistan',
    code: 'AF',
    phoneCode: '+93',
    localName: 'افغانستان',
    turkishName: 'Afganistan',
  },
  {
    name: 'Alland Islands',
    code: 'AX',
    phoneCode: '+358',
    localName: 'Åland Islands',
    turkishName: 'Åland Adaları',
  },
  {
    name: 'Albania',
    code: 'AL',
    phoneCode: '+355',
    localName: 'Shqipëria',
    turkishName: 'Arnavutluk',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    phoneCode: '+213',
    localName: 'الجزائر',
    turkishName: 'Cezayir',
  },
  {
    name: 'American Samoa',
    code: 'AS',
    phoneCode: '+1 684',
    localName: 'Amelika Sāmoa',
    turkishName: 'Amerikan Samoa',
  },
  {
    name: 'Andorra',
    code: 'AD',
    phoneCode: '+376',
    localName: 'Andorra',
    turkishName: 'Andora',
  },
  {
    name: 'Angola',
    code: 'AO',
    phoneCode: '+244',
    localName: 'Angola',
    turkishName: 'Angola',
  },
  {
    name: 'Anguilla',
    code: 'AI',
    phoneCode: '+1 264',
    localName: 'Anguilla',
    turkishName: 'Anguilla',
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    phoneCode: '+672',
    localName: 'Antarctica',
    turkishName: 'Antarktika',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    phoneCode: '+1 268',
    localName: 'Antigua and Barbuda',
    turkishName: 'Antigua ve Barbuda',
  },
  {
    name: 'Argentina',
    code: 'AR',
    phoneCode: '+54',
    localName: 'Argentina',
    turkishName: 'Arjantin',
  },
  {
    name: 'Armenia',
    code: 'AM',
    phoneCode: '+374',
    localName: 'Հայաստան',
    turkishName: 'Ermenistan',
  },
  {
    name: 'Aruba',
    code: 'AW',
    phoneCode: '+297',
    localName: 'Aruba',
    turkishName: 'Aruba',
  },
  {
    name: 'Australia',
    code: 'AU',
    phoneCode: '+61',
    localName: 'Australia',
    turkishName: 'Avustralya',
  },
  {
    name: 'Austria',
    code: 'AT',
    phoneCode: '+43',
    localName: 'Österreich',
    turkishName: 'Avusturya',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    phoneCode: '+994',
    localName: 'Azərbaycan',
    turkishName: 'Azerbaycan',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    phoneCode: '+1 242',
    localName: 'Bahamas',
    turkishName: 'Bahamalar',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    phoneCode: '+973',
    localName: 'البحرين',
    turkishName: 'Bahreyn',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    phoneCode: '+880',
    localName: 'বাংলাদেশ',
    turkishName: 'Bangladeş',
  },
  {
    name: 'Barbados',
    code: 'BB',
    phoneCode: '+1 246',
    localName: 'Barbados',
    turkishName: 'Barbados',
  },
  {
    name: 'Belarus',
    code: 'BY',
    phoneCode: '+375',
    localName: 'Беларусь',
    turkishName: 'Belarus',
  },
  {
    name: 'Belgium',
    code: 'BE',
    phoneCode: '+32',
    localName: 'België',
    turkishName: 'Belçika',
  },
  {
    name: 'Belize',
    code: 'BZ',
    phoneCode: '+501',
    localName: 'Belize',
    turkishName: 'Belize',
  },
  {
    name: 'Benin',
    code: 'BJ',
    phoneCode: '+229',
    localName: 'Bénin',
    turkishName: 'Benin',
  },
  {
    name: 'Bermuda',
    code: 'BM',
    phoneCode: '+1 441',
    localName: 'Bermuda',
    turkishName: 'Bermuda',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    phoneCode: '+975',
    localName: 'འབྲུག',
    turkishName: 'Butan',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    phoneCode: '+591',
    localName: 'Bolivia',
    turkishName: 'Bolivya',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    phoneCode: '+387',
    localName: 'Bosna i Hercegovina',
    turkishName: 'Bosna-Hersek',
  },
  {
    name: 'Botswana',
    code: 'BW',
    phoneCode: '+267',
    localName: 'Botswana',
    turkishName: 'Botsvana',
  },
  {
    name: 'Bouvet Island',
    code: 'BV',
    phoneCode: '+47',
    localName: 'Bouvet Island',
    turkishName: 'Bouvet Adası',
  },
  {
    name: 'Brazil',
    code: 'BR',
    phoneCode: '+55',
    localName: 'Brasil',
    turkishName: 'Brezilya',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    phoneCode: '+246',
    localName: 'British Indian Ocean Territory',
    turkishName: 'Britanya Hint Okyanusu Toprakları',
  },
  {
    name: 'British Virgin Islands',
    code: 'VG',
    phoneCode: '+1 284',
    localName: 'British Virgin Islands',
    turkishName: 'Britanya Virgin Adaları',
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    phoneCode: '+673',
    localName: 'Negara Brunei Darussalam',
    turkishName: 'Brunei',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    phoneCode: '+359',
    localName: 'България',
    turkishName: 'Bulgaristan',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    phoneCode: '+226',
    localName: 'Burkina Faso',
    turkishName: 'Burkina Faso',
  },
  {
    name: 'Burundi',
    code: 'BI',
    phoneCode: '+257',
    localName: 'Uburundi',
    turkishName: 'Burundi',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    phoneCode: '+855',
    localName: 'Kâmpŭchéa',
    turkishName: 'Kamboçya',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    phoneCode: '+237',
    localName: 'Cameroon',
    turkishName: 'Kamerun',
  },
  {
    name: 'Canada',
    code: 'CA',
    phoneCode: '+1',
    localName: 'Canada',
    turkishName: 'Kanada',
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    phoneCode: '+238',
    localName: 'Cabo Verde',
    turkishName: 'Cape Verde',
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    phoneCode: '+1 345',
    localName: 'Cayman Islands',
    turkishName: 'Cayman Adaları',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    phoneCode: '+236',
    localName: 'Central African Republic',
    turkishName: 'Orta Afrika Cumhuriyeti',
  },
  {
    name: 'Chad',
    code: 'TD',
    phoneCode: '+235',
    localName: 'Tchad',
    turkishName: 'Çad',
  },
  {
    name: 'Chile',
    code: 'CL',
    phoneCode: '+56',
    localName: 'Chile',
    turkishName: 'Şili',
  },
  {
    name: 'China',
    code: 'CN',
    phoneCode: '+86',
    localName: '中国',
    turkishName: 'Çin',
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    phoneCode: '+61',
    localName: 'Christmas Island',
    turkishName: 'Noel Adası',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    phoneCode: '+61',
    localName: 'Cocos (Keeling) Islands',
    turkishName: 'Cocos (Keeling) Adaları',
  },
  {
    name: 'Colombia',
    code: 'CO',
    phoneCode: '+57',
    localName: 'Colombia',
    turkishName: 'Kolombiya',
  },
  {
    name: 'Comoros',
    code: 'KM',
    phoneCode: '+269',
    localName: 'Comoros',
    turkishName: 'Komorlar',
  },
  {
    name: 'Congo',
    code: 'CG',
    phoneCode: '+242',
    localName: 'Congo',
    turkishName: 'Kongo',
  },
  {
    name: 'Congo, Democratic Republic of the',
    code: 'CD',
    phoneCode: '+243',
    localName: 'Congo, Democratic Republic of the',
    turkishName: 'Demokratik Kongo Cumhuriyeti',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    phoneCode: '+682',
    localName: 'Cook Islands',
    turkishName: 'Cook Adaları',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    phoneCode: '+506',
    localName: 'Costa Rica',
    turkishName: 'Kosta Rika',
  },
  {
    name: "Côte d'Ivoire",
    code: 'CI',
    phoneCode: '+225',
    localName: "Côte d'Ivoire",
    turkishName: 'Fildişi Sahili',
  },
  {
    name: 'Croatia',
    code: 'HR',
    phoneCode: '+385',
    localName: 'Hrvatska',
    turkishName: 'Hırvatistan',
  },
  {
    name: 'Cuba',
    code: 'CU',
    phoneCode: '+53',
    localName: 'Cuba',
    turkishName: 'Küba',
  },
  {
    name: 'Curaçao',
    code: 'CW',
    phoneCode: '+599',
    localName: 'Curaçao',
    turkishName: 'Curaçao',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    phoneCode: '+357',
    localName: 'Κύπρος',
    turkishName: 'Kıbrıs Rum Kesimi',
  },
  {
    name: 'Northern Cyprus',
    code: 'TRNC',
    phoneCode: '+90',
    localName: 'Kuzey Kıbrıs Türk Cumhuriyeti',
    turkishName: 'Kuzey Kıbrıs Türk Cumhuriyeti',
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    phoneCode: '+420',
    localName: 'Česká republika',
    turkishName: 'Çek Cumhuriyeti',
  },
  {
    name: 'Denmark',
    code: 'DK',
    phoneCode: '+45',
    localName: 'Danmark',
    turkishName: 'Danimarka',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    phoneCode: '+253',
    localName: 'Djibouti',
    turkishName: 'Cibuti',
  },
  {
    name: 'Dominica',
    code: 'DM',
    phoneCode: '+1 767',
    localName: 'Dominica',
    turkishName: 'Dominika',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    phoneCode: '+1 849',
    localName: 'Dominican Republic',
    turkishName: 'Dominik Cumhuriyeti',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    phoneCode: '+593',
    localName: 'Ecuador',
    turkishName: 'Ekvador',
  },
  {
    name: 'Egypt',
    code: 'EG',
    phoneCode: '+20',
    localName: 'مصر',
    turkishName: 'Mısır',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    phoneCode: '+503',
    localName: 'El Salvador',
    turkishName: 'El Salvador',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    phoneCode: '+240',
    localName: 'Equatorial Guinea',
    turkishName: 'Ekvator Ginesi',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    phoneCode: '+291',
    localName: 'ኤርትራ',
    turkishName: 'Eritre',
  },
  {
    name: 'Estonia',
    code: 'EE',
    phoneCode: '+372',
    localName: 'Eesti',
    turkishName: 'Estonya',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    phoneCode: '+251',
    localName: 'ኢትዮጵያ',
    turkishName: 'Etiyopya',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    phoneCode: '+500',
    localName: 'Falkland Islands (Malvinas)',
    turkishName: 'Falkland Adaları (Malvinas)',
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    phoneCode: '+298',
    localName: 'Føroyar',
    turkishName: 'Faroe Adaları',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    phoneCode: '+679',
    localName: 'Fiji',
    turkishName: 'Fiji',
  },
  {
    name: 'Finland',
    code: 'FI',
    phoneCode: '+358',
    localName: 'Suomi',
    turkishName: 'Finlandiya',
  },
  {
    name: 'France',
    code: 'FR',
    phoneCode: '+33',
    localName: 'France',
    turkishName: 'Fransa',
  },
  {
    name: 'French Guiana',
    code: 'GF',
    phoneCode: '+594',
    localName: 'French Guiana',
    turkishName: 'Fransız Guyanası',
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    phoneCode: '+689',
    localName: 'French Polynesia',
    turkishName: 'Fransız Polinezyası',
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    phoneCode: '+262',
    localName: 'French Southern Territories',
    turkishName: 'Fransız Güney Toprakları',
  },
  {
    name: 'Gabon',
    code: 'GA',
    phoneCode: '+241',
    localName: 'Gabon',
    turkishName: 'Gabon',
  },
  {
    name: 'Gambia',
    code: 'GM',
    phoneCode: '+220',
    localName: 'Gambia',
    turkishName: 'Gambiya',
  },
  {
    name: 'Georgia',
    code: 'GE',
    phoneCode: '+995',
    localName: 'საქართველო',
    turkishName: 'Gürcistan',
  },
  {
    name: 'Germany',
    code: 'DE',
    phoneCode: '+49',
    localName: 'Deutschland',
    turkishName: 'Almanya',
  },
  {
    name: 'Ghana',
    code: 'GH',
    phoneCode: '+233',
    localName: 'Ghana',
    turkishName: 'Gana',
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    phoneCode: '+350',
    localName: 'Gibraltar',
    turkishName: 'Cebelitarık',
  },
  {
    name: 'Greece',
    code: 'GR',
    phoneCode: '+30',
    localName: 'Ελλάδα',
    turkishName: 'Yunanistan',
  },
  {
    name: 'Greenland',
    code: 'GL',
    phoneCode: '+299',
    localName: 'Kalaallit Nunaat',
    turkishName: 'Grönland',
  },
  {
    name: 'Grenada',
    code: 'GD',
    phoneCode: '+1 473',
    localName: 'Grenada',
    turkishName: 'Grenada',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    phoneCode: '+590',
    localName: 'Guadeloupe',
    turkishName: 'Guadeloupe',
  },
  {
    name: 'Guam',
    code: 'GU',
    phoneCode: '+1 671',
    localName: 'Guam',
    turkishName: 'Guam',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    phoneCode: '+502',
    localName: 'Guatemala',
    turkishName: 'Guatemala',
  },
  {
    name: 'Guernsey',
    code: 'GG',
    phoneCode: '+44',
    localName: 'Guernsey',
    turkishName: 'Guernsey',
  },
  {
    name: 'Guinea',
    code: 'GN',
    phoneCode: '+224',
    localName: 'Guinée',
    turkishName: 'Gine',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    phoneCode: '+245',
    localName: 'Guiné-Bissau',
    turkishName: 'Gine-Bissau',
  },
  {
    name: 'Guyana',
    code: 'GY',
    phoneCode: '+592',
    localName: 'Guyana',
    turkishName: 'Guyana',
  },
  {
    name: 'Haiti',
    code: 'HT',
    phoneCode: '+509',
    localName: 'Haïti',
    turkishName: 'Haiti',
  },
  {
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    phoneCode: '+672',
    localName: 'Heard Island and McDonald Islands',
    turkishName: 'Heard Adası ve McDonald Adaları',
  },
  {
    name: 'Honduras',
    code: 'HN',
    phoneCode: '+504',
    localName: 'Honduras',
    turkishName: 'Honduras',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    phoneCode: '+852',
    localName: '香港',
    turkishName: 'Hong Kong',
  },
  {
    name: 'Hungary',
    code: 'HU',
    phoneCode: '+36',
    localName: 'Magyarország',
    turkishName: 'Macaristan',
  },
  {
    name: 'Iceland',
    code: 'IS',
    phoneCode: '+354',
    localName: 'Ísland',
    turkishName: 'İzlanda',
  },
  {
    name: 'India',
    code: 'IN',
    phoneCode: '+91',
    localName: 'भारत',
    turkishName: 'Hindistan',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    phoneCode: '+62',
    localName: 'Indonesia',
    turkishName: 'Endonezya',
  },
  {
    name: 'Iran',
    code: 'IR',
    phoneCode: '+98',
    localName: 'ایران',
    turkishName: 'İran',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    phoneCode: '+964',
    localName: 'العراق',
    turkishName: 'Irak',
  },
  {
    name: 'Ireland',
    code: 'IE',
    phoneCode: '+353',
    localName: 'Ireland',
    turkishName: 'İrlanda',
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    phoneCode: '+44',
    localName: 'Isle of Man',
    turkishName: 'Man Adası',
  },
  {
    name: 'Israel',
    code: 'IL',
    phoneCode: '+972',
    localName: 'ישראל',
    turkishName: 'İsrail',
  },
  {
    name: 'Italy',
    code: 'IT',
    phoneCode: '+39',
    localName: 'Italia',
    turkishName: 'İtalya',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    phoneCode: '+1 876',
    localName: 'Jamaica',
    turkishName: 'Jamaika',
  },
  {
    name: 'Japan',
    code: 'JP',
    phoneCode: '+81',
    localName: '日本',
    turkishName: 'Japonya',
  },
  {
    name: 'Jersey',
    code: 'JE',
    phoneCode: '+44',
    localName: 'Jersey',
    turkishName: 'Jersey',
  },
  {
    name: 'Jordan',
    code: 'JO',
    phoneCode: '+962',
    localName: 'الأردن',
    turkishName: 'Ürdün',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    phoneCode: '+7',
    localName: 'Қазақстан',
    turkishName: 'Kazakistan',
  },
  {
    name: 'Kenya',
    code: 'KE',
    phoneCode: '+254',
    localName: 'Kenya',
    turkishName: 'Kenya',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    phoneCode: '+686',
    localName: 'Kiribati',
    turkishName: 'Kiribati',
  },
  {
    name: 'Korea, North',
    code: 'KP',
    phoneCode: '+850',
    localName: '조선 민주주의 인민 공화국',
    turkishName: 'Kuzey Kore',
  },
  {
    name: 'Korea, South',
    code: 'KR',
    phoneCode: '+82',
    localName: '대한민국',
    turkishName: 'Güney Kore',
  },
  {
    name: 'Kosovo',
    code: 'XK',
    phoneCode: '+383',
    localName: 'Kosova',
    turkishName: 'Kosova',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    phoneCode: '+965',
    localName: 'الكويت',
    turkishName: 'Kuveyt',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    phoneCode: '+996',
    localName: 'Кыргызстан',
    turkishName: 'Kırgızistan',
  },
  {
    name: 'Laos',
    code: 'LA',
    phoneCode: '+856',
    localName: 'ສ.ປ.ປ ລາວ',
    turkishName: 'Laos',
  },
  {
    name: 'Latvia',
    code: 'LV',
    phoneCode: '+371',
    localName: 'Latvija',
    turkishName: 'Latvia',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    phoneCode: '+961',
    localName: 'لبنان',
    turkishName: 'Lübnan',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    phoneCode: '+266',
    localName: 'Lesotho',
    turkishName: 'Lesotho',
  },
  {
    name: 'Liberia',
    code: 'LR',
    phoneCode: '+231',
    localName: 'Liberia',
    turkishName: 'Liberya',
  },
  {
    name: 'Libya',
    code: 'LY',
    phoneCode: '+218',
    localName: 'ليبيا',
    turkishName: 'Libya',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    phoneCode: '+423',
    localName: 'Liechtenstein',
    turkishName: 'Lihtenştayn',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    phoneCode: '+370',
    localName: 'Lietuva',
    turkishName: 'Litvanya',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    phoneCode: '+352',
    localName: 'Luxembourg',
    turkishName: 'Lüksemburg',
  },
  {
    name: 'Macao',
    code: 'MO',
    phoneCode: '+853',
    localName: '澳門',
    turkishName: 'Makao',
  },
  {
    name: 'Macedonia',
    code: 'MK',
    phoneCode: '+389',
    localName: 'Македонија',
    turkishName: 'Makedonya',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    phoneCode: '+261',
    localName: 'Madagasikara',
    turkishName: 'Madagaskar',
  },
  {
    name: 'Malawi',
    code: 'MW',
    phoneCode: '+265',
    localName: 'Malawi',
    turkishName: 'Malavi',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    phoneCode: '+60',
    localName: 'Malaysia',
    turkishName: 'Malezya',
  },
  {
    name: 'Maldives',
    code: 'MV',
    phoneCode: '+960',
    localName: 'ދިވެހިރާއްޖެ',
    turkishName: 'Maldivler',
  },
  {
    name: 'Mali',
    code: 'ML',
    phoneCode: '+223',
    localName: 'Mali',
    turkishName: 'Mali',
  },
  {
    name: 'Malta',
    code: 'MT',
    phoneCode: '+356',
    localName: 'Malta',
    turkishName: 'Malta',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    phoneCode: '+692',
    localName: 'Marshall Islands',
    turkishName: 'Marshall Adaları',
  },
  {
    name: 'Martinique',
    code: 'MQ',
    phoneCode: '+596',
    localName: 'Martinique',
    turkishName: 'Martinik',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    phoneCode: '+222',
    localName: 'موريتانيا',
    turkishName: 'Moritanya',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    phoneCode: '+230',
    localName: 'Maurice',
    turkishName: 'Mauritius',
  },
  {
    name: 'Mayotte',
    code: 'YT',
    phoneCode: '+262',
    localName: 'Mayotte',
    turkishName: 'Mayotte',
  },
  {
    name: 'Mexico',
    code: 'MX',
    phoneCode: '+52',
    localName: 'México',
    turkishName: 'Meksika',
  },
  {
    name: 'Micronesia',
    code: 'FM',
    phoneCode: '+691',
    localName: 'Micronesia',
    turkishName: 'Mikronezya',
  },
  {
    name: 'Moldova',
    code: 'MD',
    phoneCode: '+373',
    localName: 'Moldova',
    turkishName: 'Moldova',
  },
  {
    name: 'Monaco',
    code: 'MC',
    phoneCode: '+377',
    localName: 'Monaco',
    turkishName: 'Monako',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    phoneCode: '+976',
    localName: 'Монгол улс',
    turkishName: 'Moğolistan',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    phoneCode: '+382',
    localName: 'Crna Gora',
    turkishName: 'Karadağ',
  },
  {
    name: 'Montserrat',
    code: 'MS',
    phoneCode: '+1 664',
    localName: 'Montserrat',
    turkishName: 'Montserrat',
  },
  {
    name: 'Morocco',
    code: 'MA',
    phoneCode: '+212',
    localName: 'المغرب',
    turkishName: 'Fas',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    phoneCode: '+258',
    localName: 'Moçambique',
    turkishName: 'Mozambik',
  },
  {
    name: 'Myanmar',
    code: 'MM',
    phoneCode: '+95',
    localName: 'မြန်မာ',
    turkishName: 'Myanmar',
  },
  {
    name: 'Namibia',
    code: 'NA',
    phoneCode: '+264',
    localName: 'Namibia',
    turkishName: 'Namibya',
  },
  {
    name: 'Nauru',
    code: 'NR',
    phoneCode: '+674',
    localName: 'Nauru',
    turkishName: 'Nauru',
  },
  {
    name: 'Nepal',
    code: 'NP',
    phoneCode: '+977',
    localName: 'नेपाल',
    turkishName: 'Nepal',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    phoneCode: '+31',
    localName: 'Nederland',
    turkishName: 'Hollanda',
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    phoneCode: '+687',
    localName: 'Nouvelle-Calédonie',
    turkishName: 'Yeni Kaledonya',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    phoneCode: '+64',
    localName: 'New Zealand',
    turkishName: 'Yeni Zelanda',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    phoneCode: '+505',
    localName: 'Nicaragua',
    turkishName: 'Nikaragua',
  },
  {
    name: 'Niger',
    code: 'NE',
    phoneCode: '+227',
    localName: 'Niger',
    turkishName: 'Nijer',
  },
  {
    name: 'Niue',
    code: 'NU',
    phoneCode: '+683',
    localName: 'Niue',
    turkishName: 'Niue',
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    phoneCode: '+672',
    localName: 'Norfolk Island',
    turkishName: 'Norfolk Adası',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    phoneCode: '+1 670',
    localName: 'Northern Mariana Islands',
    turkishName: 'Kuzey Mariana Adaları',
  },
  {
    name: 'Norway',
    code: 'NO',
    phoneCode: '+47',
    localName: 'Norge',
    turkishName: 'Norveç',
  },
  {
    name: 'Oman',
    code: 'OM',
    phoneCode: '+968',
    localName: 'عُمان',
    turkishName: 'Umman',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    phoneCode: '+92',
    localName: 'اکِستان',
    turkishName: 'Pakistan',
  },
  {
    name: 'Palau',
    code: 'PW',
    phoneCode: '+680',
    localName: 'Palau',
    turkishName: 'Palau',
  },
  {
    name: 'Palestine',
    code: 'PS',
    phoneCode: '+970',
    localName: 'فلسطين',
    turkishName: 'Filistin',
  },
  {
    name: 'Panama',
    code: 'PA',
    phoneCode: '+507',
    localName: 'Panamá',
    turkishName: 'Panama',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    phoneCode: '+675',
    localName: 'Papua New Guinea',
    turkishName: 'Papua Yeni Gine',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    phoneCode: '+595',
    localName: 'Paraguay',
    turkishName: 'Paraguay',
  },
  {
    name: 'Peru',
    code: 'PE',
    phoneCode: '+51',
    localName: 'Perú',
    turkishName: 'Peru',
  },
  {
    name: 'Philippines',
    code: 'PH',
    phoneCode: '+63',
    localName: 'Pilipinas',
    turkishName: 'Filipinler',
  },
  {
    name: 'Pitcairn',
    code: 'PN',
    phoneCode: '+64',
    localName: 'Pitcairn',
    turkishName: 'Pitcairn',
  },
  {
    name: 'Poland',
    code: 'PL',
    phoneCode: '+48',
    localName: 'Polska',
    turkishName: 'Polonya',
  },
  {
    name: 'Portugal',
    code: 'PT',
    phoneCode: '+351',
    localName: 'Portugal',
    turkishName: 'Portekiz',
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    phoneCode: '+1 787',
    localName: 'Puerto Rico',
    turkishName: 'Porto Riko',
  },
  {
    name: 'Qatar',
    code: 'QA',
    phoneCode: '+974',
    localName: 'قطر',
    turkishName: 'Katar',
  },
  {
    name: 'Réunion',
    code: 'RE',
    phoneCode: '+262',
    localName: 'La Réunion',
    turkishName: 'Réunion',
  },
  {
    name: 'Romania',
    code: 'RO',
    phoneCode: '+40',
    localName: 'România',
    turkishName: 'Romanya',
  },
  {
    name: 'Russian Federation',
    code: 'RU',
    phoneCode: '+7',
    localName: 'Россия',
    turkishName: 'Rusya Federasyonu',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    phoneCode: '+250',
    localName: 'Rwanda',
    turkishName: 'Ruanda',
  },
  {
    name: 'Saint Barthélemy',
    code: 'BL',
    phoneCode: '+590',
    localName: 'Saint-Barthélemy',
    turkishName: 'Saint Barthélemy',
  },
  {
    name: 'Saint Helena',
    code: 'SH',
    phoneCode: '+290',
    localName: 'Saint Helena',
    turkishName: 'Saint Helena',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    phoneCode: '+1 869',
    localName: 'Saint Kitts and Nevis',
    turkishName: 'Saint Kitts ve Nevis',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    phoneCode: '+1 758',
    localName: 'Saint Lucia',
    turkishName: 'Saint Lucia',
  },
  {
    name: 'Saint Martin (French part)',
    code: 'MF',
    phoneCode: '+590',
    localName: 'Saint-Martin',
    turkishName: 'Saint Martin (Fransız kısmı)',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    phoneCode: '+508',
    localName: 'Saint-Pierre-et-Miquelon',
    turkishName: 'Saint Pierre ve Miquelon',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    phoneCode: '+1 784',
    localName: 'Saint Vincent and the Grenadines',
    turkishName: 'Saint Vincent ve Grenadinler',
  },
  {
    name: 'Samoa',
    code: 'WS',
    phoneCode: '+685',
    localName: 'Samoa',
    turkishName: 'Samoa',
  },
  {
    name: 'San Marino',
    code: 'SM',
    phoneCode: '+378',
    localName: 'San Marino',
    turkishName: 'San Marino',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    phoneCode: '+239',
    localName: 'São Tomé and Príncipe',
    turkishName: 'São Tomé ve Príncipe',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    phoneCode: '+966',
    localName: 'السعودية',
    turkishName: 'Suudi Arabistan',
  },
  {
    name: 'Senegal',
    code: 'SN',
    phoneCode: '+221',
    localName: 'Sénégal',
    turkishName: 'Senegal',
  },
  {
    name: 'Serbia',
    code: 'RS',
    phoneCode: '+381',
    localName: 'Србија',
    turkishName: 'Sırbistan',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    phoneCode: '+248',
    localName: 'Seychelles',
    turkishName: 'Seyşeller',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    phoneCode: '+232',
    localName: 'Sierra Leone',
    turkishName: 'Sierra Leone',
  },
  {
    name: 'Singapore',
    code: 'SG',
    phoneCode: '+65',
    localName: 'Singapore',
    turkishName: 'Singapur',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    code: 'SX',
    phoneCode: '+1 721',
    localName: 'Sint Maarten',
    turkishName: 'Saint Martin (Hollanda kısmı)',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    phoneCode: '+421',
    localName: 'Slovensko',
    turkishName: 'Slovakya',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    phoneCode: '+386',
    localName: 'Slovenija',
    turkishName: 'Slovenya',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    phoneCode: '+677',
    localName: 'Solomon Islands',
    turkishName: 'Solomon Adaları',
  },
  {
    name: 'Somalia',
    code: 'SO',
    phoneCode: '+252',
    localName: 'Soomaaliya',
    turkishName: 'Somali',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    phoneCode: '+27',
    localName: 'South Africa',
    turkishName: 'Güney Afrika',
  },
  {
    name: 'South Georgia',
    code: 'GS',
    phoneCode: '+500',
    localName: 'South Georgia',
    turkishName: 'Güney Georgia',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    phoneCode: '+211',
    localName: 'South Sudan',
    turkishName: 'Güney Sudan',
  },
  {
    name: 'Spain',
    code: 'ES',
    phoneCode: '+34',
    localName: 'España',
    turkishName: 'İspanya',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    phoneCode: '+94',
    localName: 'ශ්‍රී ලංකා',
    turkishName: 'Sri Lanka',
  },
  {
    name: 'Sudan',
    code: 'SD',
    phoneCode: '+249',
    localName: 'السودان',
    turkishName: 'Sudan',
  },
  {
    name: 'Suriname',
    code: 'SR',
    phoneCode: '+597',
    localName: 'Suriname',
    turkishName: 'Surinam',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    phoneCode: '+47',
    localName: 'Svalbard og Jan Mayen',
    turkishName: 'Svalbard ve Jan Mayen',
  },
  {
    name: 'Swaziland',
    code: 'SZ',
    phoneCode: '+268',
    localName: 'Eswatini',
    turkishName: 'Svaziland',
  },
  {
    name: 'Sweden',
    code: 'SE',
    phoneCode: '+46',
    localName: 'Sverige',
    turkishName: 'İsveç',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    phoneCode: '+41',
    localName: 'Schweiz',
    turkishName: 'İsviçre',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    phoneCode: '+963',
    localName: 'سورية',
    turkishName: 'Suriye Arap Cumhuriyeti',
  },
  {
    name: 'Taiwan',
    code: 'TW',
    phoneCode: '+886',
    localName: '台灣',
    turkishName: 'Tayvan',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    phoneCode: '+992',
    localName: 'Тоҷикистон',
    turkishName: 'Tacikistan',
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    phoneCode: '+255',
    localName: 'Tanzania',
    turkishName: 'Tanzanya Birleşik Cumhuriyeti',
  },
  {
    name: 'Thailand',
    code: 'TH',
    phoneCode: '+66',
    localName: 'ประเทศไทย',
    turkishName: 'Tayland',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    phoneCode: '+670',
    localName: 'Timor-Leste',
    turkishName: 'Doğu Timor',
  },
  {
    name: 'Togo',
    code: 'TG',
    phoneCode: '+228',
    localName: 'Togo',
    turkishName: 'Togo',
  },
  {
    name: 'Tokelau',
    code: 'TK',
    phoneCode: '+690',
    localName: 'Tokelau',
    turkishName: 'Tokelau',
  },
  {
    name: 'Tonga',
    code: 'TO',
    phoneCode: '+676',
    localName: 'Tonga',
    turkishName: 'Tonga',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    phoneCode: '+1 868',
    localName: 'Trinidad and Tobago',
    turkishName: 'Trinidad ve Tobago',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    phoneCode: '+216',
    localName: 'تونس',
    turkishName: 'Tunus',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    phoneCode: '+993',
    localName: 'Turkmenistan',
    turkishName: 'Türkmenistan',
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    phoneCode: '+1 649',
    localName: 'Turks and Caicos Islands',
    turkishName: 'Turks ve Caicos Adaları',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    phoneCode: '+688',
    localName: 'Tuvalu',
    turkishName: 'Tuvalu',
  },
  {
    name: 'Uganda',
    code: 'UG',
    phoneCode: '+256',
    localName: 'Uganda',
    turkishName: 'Uganda',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    phoneCode: '+380',
    localName: 'Україна',
    turkishName: 'Ukrayna',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    phoneCode: '+971',
    localName: 'الإمارات العربية المتحدة',
    turkishName: 'Birleşik Arap Emirlikleri',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    phoneCode: '+44',
    localName: 'United Kingdom',
    turkishName: 'Birleşik Krallık',
  },
  {
    name: 'United States',
    code: 'US',
    phoneCode: '+1',
    localName: 'United States',
    turkishName: 'Amerika Birleşik Devletleri',
  },
  {
    name: 'US Minor Outlying Islands',
    code: 'UM',
    phoneCode: '+1',
    localName: 'US Minor Outlying Islands',
    turkishName: 'ABD Küçük Dış Adaları',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    phoneCode: '+598',
    localName: 'Uruguay',
    turkishName: 'Uruguay',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    phoneCode: '+678',
    localName: 'Vanuatu',
    turkishName: 'Vanuatu',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    phoneCode: '+58',
    localName: 'Venezuela',
    turkishName: 'Venezuela',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    phoneCode: '+84',
    localName: 'Việt Nam',
    turkishName: 'Vietnam',
  },
  {
    name: 'Virgin Islands, U.S.',
    code: 'VI',
    phoneCode: '+1 340',
    localName: 'Virgin Islands, U.S.',
    turkishName: 'ABD Virjin Adaları',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    phoneCode: '+681',
    localName: 'Wallis et Futuna',
    turkishName: 'Wallis ve Futuna',
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    phoneCode: '+212',
    localName: 'الصحراء الغربية',
    turkishName: 'Batı Sahara',
  },
  {
    name: 'Yemen',
    code: 'YE',
    phoneCode: '+967',
    localName: 'اليمن',
    turkishName: 'Yemen',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    phoneCode: '+260',
    localName: 'Zambia',
    turkishName: 'Zambiya',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    phoneCode: '+263',
    localName: 'Zimbabwe',
    turkishName: 'Zimbabve',
  },
];

export default phoneCodes;
