import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  channelIconWrap: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    border: '1px solid rgba(17, 17, 17, 0.12)',
    flexShrink: 0,
  },
  page: {
    flex: 1,
    px: 0,
    py: { xs: 2, md: 3 },
    gap: 2.5,
  },
  header: {
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'flex-start', md: 'center' },
    justifyContent: 'space-between',
    gap: 2,
  },
  titleGroup: { gap: 1 },
  profileCard: {
    width: { xs: '100%', md: 'auto' },
    minWidth: { md: 220 },
  },
  profileCardBody: {
    alignItems: { xs: 'flex-start', md: 'flex-end' },
    gap: 0.35,
    justifyContent: { md: 'flex-end' },
  },
  profileText: {
    gap: 0.25,
    textAlign: { xs: 'left', md: 'right' },
  },
  profileName: {
    color: palette.text.main,
    fontSize: { xs: 18, md: 22 },
    fontWeight: 700,
    lineHeight: 1.2,
  },
  profileRole: {
    color: palette.text.mediumLight,
    fontSize: { xs: 15, md: 17 },
    lineHeight: 1.2,
  },
  title: {
    fontSize: { xs: '2rem', md: '2.6rem' },
    fontWeight: 500,
    letterSpacing: '-0.05em',
    lineHeight: 1.03,
  },
  subtitle: {
    color: palette.text.mediumLight,
    fontSize: { xs: 15, md: 16 },
    lineHeight: 1.5,
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: 'minmax(0, 1.55fr) minmax(300px, 0.85fr)' },
    gap: 2,
    alignItems: 'start',
  },
  leftColumn: { gap: 2 },
  rightColumn: { gap: 1.5 },
  card: {
    border: `1px solid ${palette.gray[100]}`,
    borderRadius: 4,
    p: { xs: 2, md: 2.5 },
    bgcolor: palette.bg.main,
  },
  sectionCardBody: { gap: 2.25 },
  cardTitle: {
    fontSize: { xs: '1.65rem', md: '1.8rem' },
    fontWeight: 500,
    letterSpacing: '-0.04em',
  },
  fieldGroup: { gap: 1.25 },
  fieldLabel: {
    color: palette.text.light,
    letterSpacing: '0.12em',
    fontWeight: 800,
    fontSize: 11,
  },
  channelGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
    gap: 1.25,
  },
  channelButton: (selected: boolean) => ({
    height: 60,
    borderRadius: 2.5,
    border: selected ? `2px solid ${palette.primary.main}` : `1px solid ${palette.gray[100]}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1.25,
    fontSize: { xs: 15, md: 16 },
    color: selected ? palette.primary.main : palette.text.mediumLight,
    fontWeight: selected ? 700 : 500,
    cursor: 'pointer',
    transition: 'all .18s ease',
    '&:hover': {
      borderColor: palette.primary.main,
      color: palette.primary.main,
    },
  }),
  contentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 1.25,
  },
  contentButton: (selected: boolean) => ({
    minWidth: 98,
    px: 2.25,
    py: 1.05,
    borderRadius: 999,
    border: '1px solid',
    borderColor: selected ? palette.primary.main : palette.gray[100],
    bgcolor: selected ? palette.primary.main : palette.bg.main,
    color: selected ? palette.primary.contrastText : palette.text.mediumLight,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all .18s ease',
    '&:hover': {
      borderColor: palette.primary.main,
      color: selected ? palette.primary.contrastText : palette.primary.main,
    },
  }),
  productCard: {
    border: `1px solid ${palette.gray[100]}`,
    borderRadius: 3,
    p: 1.75,
  },
  productRow: {
    flexDirection: { xs: 'column', sm: 'row' },
    gap: 2,
    alignItems: { sm: 'center' },
  },
  productImageWrap: {
    width: 88,
    height: 88,
    borderRadius: 2.5,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  productImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  productInfo: { gap: 0.65 },
  productName: {
    fontSize: { xs: 20, md: 17 },
    lineHeight: 1.2,
    fontWeight: 500,
    maxWidth: 380,
  },
  productMeta: {
    color: palette.text.mediumLight,
    fontSize: 14,
  },
  generatedGroup: { gap: 1.1 },
  generatedWrap: { gap: 1.25 },
  generatedUrl: {
    width: '100%',
    minHeight: 88,
    borderRadius: 2.25,
    border: `1px solid ${palette.gray[100]}`,
    px: 2,
    py: 1.5,
    fontFamily: 'monospace',
    fontSize: { xs: 14, md: 15 },
    color: palette.text.main,
    lineHeight: 1.6,
    wordBreak: 'break-all',
    userSelect: 'text',
  },
  actionsRow: {
    flexDirection: { xs: 'column', sm: 'row' },
    gap: 1.25,
  },
  copyButton: {
    minWidth: { xs: '100%', sm: 168 },
    height: 52,
    borderRadius: 2.25,
    bgcolor: palette.primary.main,
    '&:hover': { bgcolor: palette.primary.light },
  },
  openButton: {
    minWidth: { xs: '100%', sm: 132 },
    height: 52,
    borderRadius: 2.25,
    borderColor: palette.gray[100],
    color: palette.text.medium,
    bgcolor: palette.bg.main,
  },
  recentLinksSection: { gap: 1.15 },
  recentLinksTitle: {
    fontSize: { xs: '1.55rem', md: '1.75rem' },
    fontWeight: 500,
    letterSpacing: '-0.04em',
  },
  recentLinkCard: {
    border: `1px solid ${palette.gray[100]}`,
    borderRadius: 3,
    p: 1.75,
    bgcolor: palette.bg.main,
  },
  recentLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
  },
  recentLinkLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.75,
    minWidth: 0,
  },
  recentLinkIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 2,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  recentLinkInfo: {
    minWidth: 0,
    gap: 0.25,
  },
  recentLinkName: {
    fontSize: 15.5,
    fontWeight: 500,
  },
  recentLinkUrl: {
    color: palette.text.mediumLight,
    fontSize: 13,
    fontFamily: 'monospace',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: { xs: 150, sm: 300, md: 420 },
  },
  recentLinkMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.25,
    flexShrink: 0,
  },
  recentLinkMeta: {
    alignItems: 'flex-end',
    gap: 0.15,
  },
  recentLinkMetaValue: {
    fontSize: 15,
    fontWeight: 500,
  },
  recentLinkMetaStatus: (active: boolean) => ({
    fontSize: 13,
    color: active ? palette.success.main : palette.text.light,
  }),
  filterWrap: {
    border: `1px solid ${palette.gray[100]}`,
    borderRadius: 2.5,
    p: 0.45,
    bgcolor: palette.bg.main,
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 0.5,
  },
  filterButton: (selected: boolean) => ({
    border: 0,
    borderRadius: 1.75,
    py: 1.1,
    px: 1,
    bgcolor: selected ? palette.primary.main : 'transparent',
    color: selected ? palette.primary.contrastText : palette.text.mediumLight,
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
  }),
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 1.1,
  },
  statCard: (highlighted: boolean) => ({
    border: highlighted ? `1px solid ${palette.primary.main}` : `1px solid ${palette.gray[100]}`,
    borderRadius: 3,
    p: 1.75,
    minHeight: 104,
    bgcolor: highlighted ? palette.primary.main : 'transparent',
    color: highlighted ? palette.primary.contrastText : palette.text.main,
  }),
  statLabel: (highlighted: boolean) => ({
    mb: 1.4,
    color: highlighted ? 'rgba(255,255,255,0.8)' : palette.text.light,
    fontSize: 12,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  }),
  statValue: {
    fontSize: { xs: 22, md: 24 },
    fontWeight: 500,
    letterSpacing: '-0.04em',
  },
  statHelper: (highlighted: boolean) => ({
    mt: 0.85,
    fontSize: 13,
    color: highlighted ? 'rgba(255,255,255,0.8)' : palette.text.light,
  }),
  conversionsCard: {
    border: `1px solid ${palette.gray[100]}`,
    borderRadius: 4,
    p: { xs: 2, md: 2.1 },
    bgcolor: palette.bg.main,
  },
  conversionsBody: { gap: 1.5 },
  conversionsTitle: {
    color: palette.text.light,
    textTransform: 'uppercase',
    letterSpacing: '0.12em',
    fontSize: 12,
    fontWeight: 800,
  },
  conversionList: { gap: 0.15 },
  conversionRowWrap: (last: boolean) => ({
    py: 1.15,
    borderBottom: last ? 'none' : `1px solid ${palette.gray[100]}`,
  }),
  conversionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 1.5,
    alignItems: 'flex-start',
  },
  conversionInfo: { gap: 0.35 },
  conversionOrder: { fontSize: 17, fontWeight: 500 },
  conversionMeta: { color: palette.text.mediumLight, fontSize: 13 },
  conversionRight: { alignItems: 'flex-end', gap: 0.35 },
  conversionAmount: { color: palette.primary.main, fontWeight: 700, fontSize: 15 },
  conversionChip: {
    borderColor: palette.gray[100],
    color: palette.text.mediumLight,
    fontWeight: 600,
    bgcolor: palette.bg.main,
  },
}));

export default useStyles;
