import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  card: {
    width: { xs: 'calc(100vw - 20px)', sm: 560 },
    maxWidth: '100%',
    borderRadius: 1,
    overflow: 'hidden',
    background: palette.gray[50],
  },
  body: {
    p: 0,
    gap: 0,
    background: palette.gray[50],
    overflowY: 'auto',
  },
  hero: {
    px: { xs: 1.5, sm: 3 },
    py: { xs: 1.5, sm: 2.5 },
    background: palette.gray[200],
    color: palette.text.main,
    borderBottom: `1px solid ${palette.gray[300]}`,
  },
  heroTop: {
    gap: { xs: 0.5, sm: 1 },
  },
  heroMeta: {
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    minWidth: 0,
    flexWrap: { xs: 'wrap', sm: 'nowrap' },
  },
  heroTitle: {
    fontSize: { xs: 17, sm: 18 },
    lineHeight: 1.1,
    fontWeight: 600,
    color: palette.text.main,
    whiteSpace: 'nowrap',
  },
  heroSubtitle: {
    fontSize: 12,
    fontWeight: 500,
    color: palette.text.medium,
    whiteSpace: { xs: 'normal', sm: 'nowrap' },
    minWidth: 0,
    flex: 1,
  },
  heroLink: {
    color: palette.text.main,
    fontSize: 12,
    fontWeight: 600,
    textDecoration: 'underline',
    textDecorationColor: palette.text.main,
    textUnderlineOffset: '3px',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  quickActions: {
    px: { xs: 1.5, sm: 3 },
    py: { xs: 1.25, sm: 2 },
    gap: { xs: 0.75, sm: 1 },
    justifyContent: 'flex-end',
    flexWrap: 'nowrap',
    borderBottom: `1px solid ${palette.gray[100]}`,
    background: palette.gray[50],
  },
  quickButton: {
    minWidth: 0,
    flex: { xs: 1, sm: '0 0 auto' },
    height: { xs: 32, sm: 34 },
    borderRadius: 1.5,
    px: { xs: 1.25, sm: 1.5 },
    fontSize: 10.5,
    fontWeight: 800,
    letterSpacing: '0.01em',
  },
  content: {
    px: { xs: 1.5, sm: 3 },
    py: { xs: 1.5, sm: 2.5 },
    gap: { xs: 1.25, sm: 1.75 },
  },
  preferenceCard: {
    borderRadius: 2,
    background: palette.white.main,
    border: `1px solid ${palette.gray[100]}`,
    overflow: 'hidden',
  },
  preferenceHeader: {
    px: { xs: 1.25, sm: 2 },
    py: { xs: 1.125, sm: 1.5 },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1.5,
  },
  preferenceLeft: {
    alignItems: 'center',
    gap: 1,
    minWidth: 0,
    flex: 1,
  },
  preferenceTitle: {
    fontSize: { xs: 13.5, sm: 14 },
    fontWeight: 700,
    color: palette.text.main,
  },
  chevronButton: {
    width: 28,
    height: 28,
    minWidth: 28,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: palette.text.mediumLight,
    cursor: 'pointer',
    '&:hover': {
      color: palette.text.main,
      background: palette.gray[50],
    },
  },
  alwaysOnChip: {
    height: { xs: 22, sm: 24 },
    borderRadius: 999,
    background: palette.gray[50],
    color: palette.text.medium,
    border: `1px solid ${palette.gray[100]}`,
    fontSize: 10.5,
    fontWeight: 700,
  },
  switch: {
    m: 0,
    '& .MuiSwitch-switchBase.Mui-checked': {
      color: palette.gray[400],
    },
    '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': {
      backgroundColor: palette.gray[400],
      opacity: 1,
    },
    '& .MuiSwitch-track': {
      backgroundColor: palette.gray[300],
      opacity: 1,
    },
  },
  preferenceBody: {
    px: { xs: 1.25, sm: 2 },
    pb: { xs: 1.25, sm: 1.75 },
    pt: 0,
  },
  preferenceText: {
    fontSize: 12.5,
    lineHeight: 1.7,
    color: palette.text.secondary,
  },
  footer: {
    px: { xs: 1.5, sm: 3 },
    py: { xs: 1.5, sm: 2 },
    borderTop: `1px solid ${palette.gray[100]}`,
    justifyContent: 'flex-end',
    background: palette.gray[50],
  },
  saveButton: {
    minWidth: { xs: '100%', sm: 190 },
    height: { xs: 32, sm: 42 },
    borderRadius: 1.5,
    px: { xs: 1.25, sm: 2.5 },
    fontSize: { xs: 10.5, sm: 11.5 },
    fontWeight: 800,
    letterSpacing: '0.01em',
  },
}));

export default useStyles;
