import { withPalette } from '@/theme/ThemeRegistry';
import { headerHeight } from '@/theme/theme';

const FILTER_BAR_HEIGHT = 52;
// Duyuru seridi mobilde gizli; yedek konum yalnizca header yuksekligi.
const MOBILE_NAV_FALLBACK_TOP = headerHeight.xs;

const useStyles = withPalette((palette) => ({
  mobileFiltersWrapper: {
    minHeight: FILTER_BAR_HEIGHT,
  },
  mobileFiltersBar: {
    position: 'fixed',
    top: `var(--mobile-nav-bottom, ${MOBILE_NAV_FALLBACK_TOP}px)`,
    left: 0,
    right: 0,
    zIndex: 1296,
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    minHeight: FILTER_BAR_HEIGHT,
    borderTop: `1px solid ${palette.gray[200]}`,
    borderBottom: `1px solid ${palette.gray[200]}`,
    background: palette.bg.main,
  },
  sortWrap: {
    minWidth: 0,
    borderRight: `1px solid ${palette.gray[200]}`,
    '& .MuiInputBase-root': {
      borderRadius: 0,
      background: 'transparent',
      height: FILTER_BAR_HEIGHT - 2,
    },
  },
  filterTrigger: {
    borderRadius: 0,
    color: palette.text.main,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.9,
    px: 1.5,
    py: 0,
    minHeight: FILTER_BAR_HEIGHT - 2,
    cursor: 'pointer',
    userSelect: 'none',
    WebkitTapHighlightColor: 'transparent',
    fontWeight: 800,
    fontSize: 17,
    letterSpacing: '0.02em',
    lineHeight: 1,
    textTransform: 'uppercase' as const,
    '&:hover, &:focus-visible': {
      background: palette.bg.light,
      outline: 'none',
    },
  },
  drawer: {
    zIndex: 1301,
  },
  drawerPaper: {
    width: { xs: '100vw', sm: 420 },
    maxWidth: '100vw',
    background: palette.bg.main,
  },
  drawerHeader: {
    minHeight: 58,
    px: 1.5,
    background: palette.text.main,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  headerAction: {
    width: 36,
    height: 36,
    color: palette.bg.main,
  },
  headerSpacer: {
    width: 36,
    height: 36,
    flexShrink: 0,
  },
  drawerTitle: {
    fontWeight: 800,
    fontSize: 23,
    color: palette.bg.main,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  drawerList: {
    background: palette.bg.main,
    overflowY: 'auto',
    height: 'calc(100% - 58px - 58px)',
    px: 2,
    pt: 1.25,
    pb: 2,
    borderTop: `1px solid ${palette.gray[200]}`,
  },
  selectedChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 0.8,
    pb: 1.25,
  },
  selectedChip: {
    height: 32,
    borderRadius: 16,
    background: palette.gray[100],
    color: palette.text.main,
    border: `1px solid ${palette.gray[300]}`,
    '& .MuiChip-label': {
      fontWeight: 600,
      fontSize: 13,
      px: 1.2,
    },
    '& .MuiChip-deleteIcon': {
      color: palette.text.medium,
      width: 18,
      height: 18,
      mr: 0.5,
    },
  },
  filterListItem: {
    minHeight: 64,
    py: 1.2,
    borderBottom: `1px solid ${palette.gray[200]}`,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    cursor: 'pointer',
    userSelect: 'none',
    color: palette.text.main,
  },
  filterListLabel: {
    fontWeight: 700,
    fontSize: 16,
    color: palette.text.main,
  },
  filterListMeta: {
    minWidth: 0,
    gap: 0.35,
  },
  filterListSelected: {
    fontSize: 13,
    color: palette.text.medium,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
  },
  drawerDetail: {
    background: palette.bg.main,
    overflowY: 'auto',
    height: 'calc(100% - 58px - 58px)',
    px: 2,
    pt: 1.25,
    pb: 2,
    borderTop: `1px solid ${palette.gray[200]}`,
    '& .MuiTypography-cardTitle': {
      fontSize: 16,
      fontWeight: 800,
    },
    '& .MuiFormControlLabel-label, & .MuiTypography-body1, & .MuiTypography-body2': {
      fontSize: 18,
      lineHeight: 1.35,
    },
    '& .MuiStack-root': {
      backgroundColor: palette.bg.main,
    },
  },
  drawerFooter: {
    height: 58,
    borderTop: `1px solid ${palette.gray[300]}`,
    background: palette.bg.main,
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
  },
  cancelAction: {
    borderRight: `1px solid ${palette.gray[300]}`,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    fontWeight: 700,
    fontSize: 17,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    userSelect: 'none',
  },
  resultsAction: {
    background: palette.text.main,
    color: palette.bg.main,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    fontWeight: 700,
    fontSize: 17,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    userSelect: 'none',
  },
}));

export default useStyles;
