import { withPalette } from '@/theme/ThemeRegistry';
import { CSSProperties } from 'react';

const useStyles = withPalette((palette) => ({
  card: {
    cursor: 'pointer',
    height: '100%',
    gap: 0.5,
    borderRadius: 1,
    color: palette.text.main,
    pb: 1,
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: 0.67,
    borderRadius: 1,
    border: '1px solid',
    borderColor: palette.text.light,
    marginBottom: 0.5,
  },
  image: { width: '100%', height: '100%', objectFit: 'contain', borderRadius: 7 } as CSSProperties,
  imageLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#dedede50',
  },
  imageLoadingProgressContainer: { background: palette.bg.main, p: 1, borderRadius: 99 },
  brand: { color: palette.text.main, fontSize: 14, textTransform: 'none', lineHeight: 'normal' },
  productName: {
    color: palette.text.medium,
    fontSize: 14,
    lineHeight: 'normal',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    textTransform: 'capitalize',
  },
  priceContainer: {
    mt: 'auto',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 0.5,
    background: '#f3e8ff',
    borderRadius: 1,
    px: 1,
    py: 0.5,
  },
  price: { fontSize: '15px !important', color: palette.primary.main, fontWeight: 700 },
  originalPrice: {
    color: palette.text.medium,
    fontSize: 15,
    fontWeight: 400,
    textDecoration: 'line-through',
    lineHeight: '20px',
  },
  convertedPrice: { color: palette.text.mediumLight },
  link: { textDecoration: 'none', color: 'inherit', height: '100%', width: '100%' },
  rating: { flexDirection: 'row', alignItems: 'center', gap: '2px', pt: '2px' },
  ratingCount: { color: palette.text.mediumLight, fontSize: 10, lineHeight: 1 },
  discountBadge: {
    position: 'absolute',
    right: 0,
    top: 0,
    background: palette.primary.main,
    color: palette.primary.light,
    py: 0.5,
    px: 1,
    fontSize: 12,
    fontWeight: 700,
    lineHeight: 'normal',
    borderRadius: '0 7px 0 8px',
  },
}));

export default useStyles;
