import { withPalette } from '@/theme/ThemeRegistry';
import { CSSProperties } from 'react';

const useStyles = withPalette((palette) => ({
  card: {
    cursor: 'pointer',
    height: '100%',
    gap: 1,
    borderRadius: 0,
    color: palette.text.main,
    background: palette.white.main,
    pb: 1.25,
    p: 0,
    border: 'none',
    transition: 'transform 180ms ease',
    '&:hover': {
      transform: 'translateY(-1px)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      transition: 'none',
      '&:hover': { transform: 'none' },
    },
  },
  imageContainer: {
    position: 'relative',
    width: '100%',
    aspectRatio: { xs: '0.8', sm: '1 / 1' },
    borderRadius: 0,
    overflow: 'hidden',
    // Cizgi yerine zemin: beyaz kesimli urun fotograflarini cerceve cizmeden
    // ayirir, izgarada her kart esit agirlikta bir blok olarak okunur.
    background: palette.gray[50] ?? palette.bg.light,
    marginBottom: 0.25,
  },
  image: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    borderRadius: 0,
    transition: 'opacity 220ms ease',
  } as CSSProperties,
  imageSecondary: {
    zIndex: 1,
  } as CSSProperties,
  imageLoadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#dedede50',
  },
  imageLoadingProgressContainer: { background: palette.bg.main, p: 1, borderRadius: 99 },
  topBar: {
    position: 'absolute',
    top: {xs:0, sm:10},
    left: {xs:0, sm:10},
    right: 10,
    zIndex: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badgeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.5,
  },
  badge: {
    width: 'fit-content',
    px: { xs: 1.25, sm: 1.5 },
    py: { xs: '3px', sm: '4px' },
    borderRadius: 999,
    fontSize: { xs: 10, sm: 11 },
    fontWeight: 800,
    lineHeight: 1.2,
    letterSpacing: '0.02em',
  },
  badgeBest: {
    color: palette.primary.contrastText,
    background: palette.primary.main,
  },
  badgeOutOfStock: {
    color: palette.text.mediumLight,
    background: palette.gray[100] ?? palette.gray[200],
  },
  badgeDiscount: {
    color: palette.accentRed.main,
    background: palette.accentRed.light,
  },
  favoriteButton: {
    width: 36,
    height: 36,
    borderRadius: 0,
    border: 'none',
    backgroundColor: 'transparent',
    color: palette.text.medium,
    transition: 'all 160ms ease',
    mr: -0.5,
    '&:hover': {
      backgroundColor: 'transparent',
      transform: 'translateY(-1px)',
      color: palette.text.main,
    },
    '&.Mui-disabled': {
      backgroundColor: 'transparent',
      color: palette.text.light,
    },
  },
  favoriteButtonActive: {
    color: palette.accentRed.main,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  favoriteIcon: {
    fill: 'transparent',
    transition: 'fill 160ms ease, color 160ms ease',
  } as CSSProperties,
  favoriteIconActive: {
    fill: palette.accentRed.main,
    color: palette.accentRed.main,
    transition: 'fill 160ms ease, color 160ms ease',
  } as CSSProperties,
  badgeSoldOut: {
    color: palette.error.contrastText,
    background: palette.error.main,
  },
  infoContainer: {
    display: 'grid',
    alignContent: 'start',
    rowGap: 0.5,
  },
  subtitle: {
    color: palette.text.mediumLight,
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.2,
    letterSpacing: '0.02em',
    textTransform: 'uppercase',
  },
  productName: {
    color: palette.text.main,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.35,
    minHeight: '38px',
    whiteSpace: 'normal',
    wordBreak: 'break-word',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  priceContainer: {
    mt: 'auto',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    alignContent: 'flex-start',
    gap: 0.5,
    borderRadius: 1,
    py: 0.5,
    minHeight: { xs: 48, sm: 52 },
  },
  price: {
    fontSize: { xs: '17px !important', sm: '18px !important' },
    color: palette.text.main,
    fontWeight: 700,
    lineHeight: 1.15,
  },
  originalPrice: {
    color: palette.text.medium,
    fontSize: 13,
    fontWeight: 400,
    textDecoration: 'line-through',
    lineHeight: 1.2,
  },
  convertedPrice: { color: palette.text.mediumLight },
  link: { textDecoration: 'none', color: 'inherit', height: '100%', width: '100%', display: 'block' },
  rating: { flexDirection: 'row', alignItems: 'center', gap: 0.5, pt: 0.7 },
  ratingValue: { color: palette.text.main, fontSize: 12, fontWeight: 700, lineHeight: 1 },
  ratingStars: {
    fontSize: 13,
    color: palette.warning.main,
    '& .MuiRating-iconEmpty': {
      color: palette.gray[200],
    },
  },
  ratingCount: { color: palette.text.mediumLight, fontSize: 11, lineHeight: 1 },
  notifyButton: {
    // Tukenen urunde kart olu gorunmesin: pasif gri blok degil, aktif cerceve.
    backgroundColor: 'transparent',
    borderColor: palette.text.main,
    color: palette.text.main,
    '&:hover': {
      backgroundColor: palette.text.main,
      borderColor: palette.text.main,
      color: palette.white.main,
    },
  },
  addToCartButton: {
    width: '100%',
    mt: 0.25,
    borderRadius: 0,
    textTransform: 'none',
    fontWeight: 700,
    borderColor: palette.text.main,
    backgroundColor: palette.text.main,
    color: palette.white.main,
    '&:hover': {
      borderColor: palette.primary.main,
      backgroundColor: palette.primary.main,
    },
    '&.Mui-disabled': {
      borderColor: palette.gray[300],
      backgroundColor: palette.gray[100],
      color: palette.text.light,
    },
  },
  addToCartButtonAdded: {
    backgroundColor: palette.success.main,
    borderColor: palette.success.main,
    color: palette.success.contrastText,
    '&:hover': {
      backgroundColor: palette.success.main,
      borderColor: palette.success.main,
    },
    '&.Mui-disabled': {
      backgroundColor: palette.success.main,
      borderColor: palette.success.main,
      color: palette.success.contrastText,
      opacity: 1,
    },
  },
}));

export default useStyles;
