import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  page: {
    gap: 4,
    width: '100%',
  },
  header: {
    gap: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.5,
  },
  pageTitle: {
    fontSize: { xs: 22, sm: 26 },
    fontWeight: 800,
    letterSpacing: -0.3,
  },
  totalBadge: {
    bgcolor: palette.text.main,
    color: palette.white.main,
    fontSize: 11,
    fontWeight: 800,
    px: 1,
    py: 0.25,
    borderRadius: '4px',
    lineHeight: 1.5,
    letterSpacing: 0.5,
  },
  description: {
    color: palette.text.mediumLight,
    fontSize: 15,
    fontWeight: 500,
    maxWidth: 480,
    lineHeight: 1.5,
  },
  filtersRow: {
    flexDirection: 'row',
    gap: 1,
    flexWrap: { xs: 'nowrap', sm: 'wrap' },
    overflowX: { xs: 'auto', sm: 'visible' },
    pb: { xs: 0.5, sm: 0 },
    '&::-webkit-scrollbar': {
      height: 6,
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: palette.gray[200],
      borderRadius: '999px',
    },
  },
  filterPill: (isActive: boolean) => ({
    px: 1.5,
    py: 1,
    borderRadius: '10px',
    border: '1px solid',
    borderColor: isActive ? palette.text.main : palette.gray[200],
    bgcolor: isActive ? palette.text.main : palette.white.main,
    color: isActive ? palette.white.main : palette.text.medium,
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    transition: 'all 0.2s ease',
    cursor: 'pointer',
    userSelect: 'none',
    flexShrink: 0,
    whiteSpace: 'nowrap',
    '&:hover': {
      borderColor: palette.text.main,
      color: isActive ? palette.white.main : palette.text.main,
    },
  }),
  filterLabel: {
    fontSize: 13,
    fontWeight: 700,
    lineHeight: 1,
  },
  filterBadge: (isActive: boolean) => ({
    minWidth: 20,
    height: 20,
    px: 0.5,
    borderRadius: '999px',
    bgcolor: isActive ? 'rgba(255,255,255,0.2)' : palette.bg.dark,
    color: isActive ? palette.white.main : palette.text.main,
    display: 'grid',
    placeItems: 'center',
    fontSize: 11,
    fontWeight: 800,
    lineHeight: 1,
  }),
  orderList: {
    gap: 1.5,
  },
  filterEmptyState: {
    gap: 1,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    py: { xs: 4, sm: 5 },
    borderRadius: '14px',
    border: `1px dashed ${palette.gray[200]}`,
    bgcolor: palette.bg.light,
  },
  filterEmptyTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: palette.text.main,
  },
  filterEmptyDescription: {
    color: palette.text.mediumLight,
    fontSize: 14,
    fontWeight: 500,
  },
  emptyState: {
    gap: 3,
    textAlign: 'center',
    alignItems: 'center',
    py: { xs: 6, sm: 10 },
    borderRadius: '16px',
    border: `1px dashed ${palette.gray[200]}`,
    bgcolor: palette.bg.light,
  },
  emptyIconBox: {
    width: 80,
    height: 80,
    borderRadius: '20px',
    background: 'linear-gradient(135deg, #F5F5F7 0%, #E5E5EA 100%)',
    display: 'grid',
    placeItems: 'center',
  },
  emptyTextBox: {
    gap: 1,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: { xs: 18, sm: 20 },
    fontWeight: 700,
    color: palette.text.main,
    letterSpacing: -0.2,
  },
  emptyDescription: {
    color: palette.text.mediumLight,
    fontSize: 15,
    fontWeight: 500,
    maxWidth: 400,
    lineHeight: 1.6,
  },
}));

export default useStyles;
