import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 1400,
    display: { xs: 'flex', sm: 'none' },
    flexDirection: 'column',
    backgroundColor: palette.bg.main ?? '#fff',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0.5,
    px: 1,
    py: 1.25,
    borderBottom: `1px solid ${palette.gray[100] ?? palette.gray[200]}`,
  },
  input: {
    '& .MuiOutlinedInput-root': {
      borderRadius: 999,
      backgroundColor: palette.gray[50] ?? palette.bg.light,
      fontSize: 15,
      pl: 1.5,
    },
    '& fieldset': { border: 'none' },
  },
  body: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
    px: 2,
    py: 1.5,
    overscrollBehavior: 'contain',
  },
  section: {
    gap: 0.5,
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    py: 1,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: palette.text.mediumLight,
  },
  clearAll: {
    fontSize: 13,
    color: palette.text.mediumLight,
    cursor: 'pointer',
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
  },
  historyLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.25,
    flex: 1,
    py: 1,
    cursor: 'pointer',
    color: palette.text.mediumLight,
  },
  historyText: {
    fontSize: 15,
    color: palette.text.main,
  },
  emptyHint: {
    py: 4,
    fontSize: 14,
    lineHeight: 1.6,
    color: palette.text.mediumLight,
  },
  loadingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    py: 5,
    color: palette.text.mediumLight,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.5,
    py: 1.25,
    cursor: 'pointer',
    borderBottom: `1px solid ${palette.gray[100] ?? palette.gray[200]}`,
    '&:last-of-type': { borderBottom: 'none' },
  },
  productImage: {
    position: 'relative',
    width: 56,
    height: 56,
    flexShrink: 0,
    borderRadius: 1,
    overflow: 'hidden',
    backgroundColor: palette.gray[50] ?? palette.bg.light,
  },
  productText: {
    flex: 1,
    minWidth: 0,
    gap: 0.25,
  },
  productBrand: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: palette.text.mediumLight,
  },
  productName: {
    fontSize: 14,
    lineHeight: 1.35,
    color: palette.text.main,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  productPrice: {
    fontSize: 14,
    fontWeight: 600,
    color: palette.text.main,
  },
  allResults: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    mt: 2,
    mb: 4,
    py: 1.5,
    cursor: 'pointer',
    borderRadius: 999,
    border: `1px solid ${palette.gray[200]}`,
    color: palette.text.main,
  },
  allResultsText: {
    fontSize: 14,
    fontWeight: 600,
  },
}));

export default useStyles;
