const styles = {
  wrap: {
    display: 'grid',
    gap: 2,
  },
  breadcrumbs: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 0.5,
    px: { xs: 2, sm: 0 },
    fontSize: 18,
    color: '#111111',
    '& a': {
      color: 'inherit',
      textDecoration: 'none',
    },
    '& a:hover': {
      textDecoration: 'underline',
    },
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: 'minmax(0, 1fr)', sm: 'minmax(0, 1fr) minmax(0, 1fr)' },
    gap: { xs: 2, sm: 5 },
    alignItems: 'start',
  },
  mediaColumn: {
    position: { xs: 'relative', sm: 'sticky' },
    top: { sm: 0 },
    minWidth: 0,
  },
  mediaShell: {
    position: 'relative',
    width: '100%',
    aspectRatio: { xs: '1 / 1', sm: 'auto' },
    height: { xs: 'auto', sm: 560, md: 760 },
    overflow: 'hidden',
    borderTop: { xs: '1px solid #EEE7E2', sm: '1px solid #E7E1DC' },
    borderBottom: { xs: '1px solid #EEE7E2', sm: '1px solid #E7E1DC' },
    borderLeft: { xs: 'none', sm: '1px solid #E7E1DC' },
    borderRight: { xs: 'none', sm: '1px solid #E7E1DC' },
    bgcolor: '#FFFFFF',
  },
  staticImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    display: 'block',
  },
  galleryLayer: {
    position: 'absolute',
    inset: 0,
    zIndex: 1,
    '& > *': {
      minHeight: '100%',
    },
  },
  details: {
    display: 'grid',
    gap: 1.75,
    minWidth: 0,
    px: { xs: 2, sm: 0 },
    pt: { xs: 2, sm: 0 },
    bgcolor: '#FFFFFF',
  },
  titleBlock: {
    display: 'grid',
    gap: '6px',
  },
  brand: {
    width: 'max-content',
    color: '#111111',
    borderBottom: '1px solid #111111',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.2,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    textDecoration: 'none',
  },
  name: {
    m: 0,
    color: '#111111',
    fontSize: 24,
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: 0,
  },
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 1,
    mb: 1,
    color: '#6F6A66',
    fontSize: 14,
    lineHeight: 1,
    width: 'max-content',
    maxWidth: '100%',
    textDecoration: 'none',
    cursor: 'pointer',
  },
  summary: {
    display: 'grid',
    gap: '14px',
  },
  badge: {
    width: 'max-content',
    maxWidth: '100%',
    px: 1.75,
    py: 0.9,
    borderRadius: 999,
    bgcolor: '#F1DFE4',
    color: '#111111',
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1,
  },
  shortDescription: {
    display: 'grid',
    gap: 1.5,
    color: '#111111',
    fontSize: 16,
    lineHeight: 1.45,
    '& p': {
      m: 0,
    },
  },
  divider: {
    height: 1,
    bgcolor: '#E2E2E2',
    mt: '6px',
  },
};

export default styles;
