import { withPalette } from '@/theme/ThemeRegistry';
import { defaultMaxWidth } from '@/theme/theme';
import { keyframes } from '@mui/material';
import { CSSProperties } from 'react';

const bellRing = keyframes`
  0% { transform: rotate(0deg); }
  20% { transform: rotate(18deg); }
  40% { transform: rotate(-14deg); }
  60% { transform: rotate(10deg); }
  80% { transform: rotate(-6deg); }
  100% { transform: rotate(0deg); }
`;

const useStyles = withPalette((palette) => ({
  productContainer: {
    alignSelf: 'stretch',
    width: '100%',
    alignItems: 'flex-start',
  },
  imageGridItem: {
    zIndex: 0,
    position: { xs: 'relative', sm: 'sticky' },
    top: { sm: 0 },
    alignSelf: { sm: 'flex-start' },
    minWidth: 0,
  },
  details: {
    gap: 1.75,
    px: { xs: 2, sm: 0 },
    pt: { xs: 2, sm: 0 },
    background: palette.bg.main,
    minWidth: 0,
  },
  titleBlock: {
    gap: '6px',
  },
  productName: {
    fontWeight: 600,
    fontSize: 24,
    lineHeight: '32px',
    letterSpacing: 'normal',
    mb: 0,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    flexWrap: 'wrap',
    mb: '8px',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    width: 'max-content',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 'normal',
    gap: 0.5,
    color: palette.text.main,
    borderBottom: `1px solid ${palette.text.main}`,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  priceContainer: { flexDirection: 'row', alignItems: 'center', gap: 1.25, flexWrap: 'wrap' },
  currentPrice: {
    fontSize: '22px !important',
    fontWeight: 700,
    lineHeight: 1,
    color: palette.primary.main,
  },
  originalPrice: {
    fontSize: 20,
    fontWeight: 400,
    textDecoration: 'line-through',
    lineHeight: '20px',
  },
  rating: { flexDirection: 'row', alignItems: 'center', gap: 0.75, pt: '2px' },
  ratingSeparator: {
    color: palette.text.medium,
    fontWeight: 600,
    lineHeight: 1,
  },
  metaCategory: {
    fontSize: 14,
    lineHeight: 1,
    color: palette.text.medium,
    fontWeight: 500,
  },
  ratingCount: { color: palette.text.medium, fontSize: 14, lineHeight: 1 },
  summaryBlock: {
    gap: '14px',
  },
  badgePill: {
    alignSelf: 'flex-start',
    px: 1.75,
    py: 0.9,
    borderRadius: 999,
    backgroundColor: '#F1DFE4',
  },
  badgePillText: {
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1,
    color: palette.text.main,
  },
  shortDescription: {
    fontSize: 16,
    lineHeight: 1.45,
    fontStyle: 'normal',
    color: palette.text.main,
    maxWidth: 760,
  },
  shortDescriptionBlock: {
    gap: '12px',
  },
  shortDescriptionDivider: {
    borderColor: palette.gray?.[200] ?? '#E2E2E2',
    mt: '6px',
  },
  stockPulseDot: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    flexShrink: 0,
    position: 'relative',
    zIndex: 0,
    '&::after': {
      content: '""',
      position: 'absolute',
      inset: -1,
      borderRadius: '50%',
      backgroundColor: 'currentColor',
      opacity: 0.18,
      zIndex: -1,
      animation: 'stockWave 1.8s ease-out infinite',
    },
    '@keyframes stockWave': {
      '0%': { opacity: 0.18, transform: 'scale(1)' },
      '100%': { opacity: 0, transform: 'scale(1.7)' },
    },
  },
  stockRow: {
    pt: '4px',
    mt: '4px',
    mb: '16px',
  },
  breadcrumbs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    fontSize: 18,
    color: palette.text.main,
  },
  discountBadge: {
    background: '#C1121F',
    color: '#FFFFFF',
    width: 'auto',
    minWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    py: 0.45,
    px: 1.25,
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 'normal',
    borderRadius: 0.5,
    mx: 0.25,
    whiteSpace: 'nowrap',
  },
  ctaRow: {
    flexDirection: 'row',
    gap: 1,
    mb: 2,
    mt: 1,
  },
  trustCard: {
    py: { xs: 1.75, sm: 2 },
    border: 'none',
  },
  expirationBox: {
    mb: 2,
    px: { xs: 2, sm: 2.5 },
    py: { xs: 1.75, sm: 2 },
    gap: 1.25,
    borderRadius: 1,
    border: 'none',
    background: 'linear-gradient(180deg, rgba(247,247,248,0.98) 0%, rgba(242,242,244,0.94) 100%)',
    boxShadow: '0 18px 40px rgba(15, 23, 42, 0.05)',
  },
  expirationEyebrow: {
    fontSize: 12,
    fontWeight: 700,
    lineHeight: 1,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: palette.text.medium,
  },
  expirationRows: {
    gap: 1,
  },
  trustSignal: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 1.25,
    py: 0.25,
  },
  trustSignalIcon: {
    width: 28,
    height: 28,
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    color: palette.text.main,
  },
  trustSignalContent: {
    gap: 0.35,
  },
  trustSignalTitle: {
    fontSize: 16,
    lineHeight: 1.2,
    fontWeight: 700,
    color: palette.text.main,
  },
  trustSignalText: {
    fontSize: 15,
    lineHeight: 1.4,
    color: palette.text.medium,
  },
  expirationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 1.25,
  },
  expirationDot: {
    width: 8,
    height: 8,
    mt: '8px',
    borderRadius: '50%',
    flexShrink: 0,
    backgroundColor: palette.text.main,
  },
  expirationItem: {
    fontSize: 16,
    lineHeight: 1.45,
    color: palette.text.main,
    flex: 1,
  },
  expirationLabel: {
    fontSize: 'inherit',
    lineHeight: 'inherit',
    fontWeight: 700,
    color: 'inherit',
  },
  buyNowButton: {
    flex: 1,
    borderRadius: 1.5,
    height: 48,
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: '0.01em',
    borderColor: palette.text.medium,
    color: palette.text.main,
    '&:hover': {
      borderColor: palette.text.main,
      background: `${palette.text.main}08`,
    },
  },
  stickyCta: {
    flex: 'none',
    minWidth: 160,
    height: 52,
    fontWeight: 700,
    fontSize: 15,
    letterSpacing: '0.01em',
  },
  ctaButton: {
    flex: 1,
    borderRadius: 1.5,
    height: 48,
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: '0.01em',
    '& .stockAlertBell': {
      transformOrigin: '50% 0%',
      willChange: 'transform',
    },
    '&:hover .stockAlertBell': {
      animation: `${bellRing} 0.55s ease-in-out 1`,
    },
    '&:active .stockAlertBell': {
      animation: `${bellRing} 0.35s ease-in-out 1`,
    },
  },
  stickyBarRoot: {
    position: 'fixed',
    top: { xs: 'auto', md: 0 },
    bottom: { xs: 0, md: 'auto' },
    left: 0,
    right: 0,
    zIndex: 1290,
    borderTop: { xs: `1px solid ${palette.gray[200] ?? palette.bg.light}`, md: 'none' },
    borderBottom: { xs: 'none', md: `1px solid ${palette.gray[200] ?? palette.bg.light}` },
    background: palette.bg.main,
    display: 'flex',
    boxShadow: { xs: '0 -4px 16px rgba(20,20,20,0.08)', md: '0 8px 24px rgba(20,20,20,0.07)' },
  },
  stickyBarInner: {
    width: '100%',
    maxWidth: defaultMaxWidth,
    mx: 'auto',
    px: { xs: 2, md: 2, lg: 3 },
    py: { xs: 1.25, md: 1.2 },
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
  },
  stickyMeta: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.5,
  },
  stickyThumb: {
    width: 54,
    height: 54,
    objectFit: 'cover',
    borderRadius: 8,
    border: `1px solid ${palette.gray[200] ?? palette.bg.light}`,
    background: palette.bg.light,
    flexShrink: 0,
  } as CSSProperties,
  stickyMetaText: {
    minWidth: 0,
    gap: 0.3,
  },
  stickyName: {
    maxWidth: { md: 460, lg: 720 },
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.2,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  stickyPrice: {
    fontSize: 20,
    fontWeight: 700,
    color: palette.text.main,
    lineHeight: 1,
  },
  stickyPriceBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1.5,
    minWidth: 0,
    flex: 1,
  },
  stickyOriginalPrice: {
    fontSize: 15,
    fontWeight: 500,
    lineHeight: 1,
    color: palette.text.medium,
    textDecoration: 'line-through',
    whiteSpace: 'nowrap',
  },
  stickyCurrentPrice: {
    fontSize: 24,
    fontWeight: 700,
    lineHeight: 1,
    color: palette.primary.main,
    whiteSpace: 'nowrap',
  },
  stickyButton: {
    borderRadius: 0.75,
    width: { xs: '100%', md: 'auto' },
    minWidth: { md: 140, lg: 168 },
    height: 44,
    px: 2.25,
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: '0.01em',
  },
}));

export default useStyles;
