'use client';

import { useIsMobileApp } from '@/lib/hooks/useIsMobileApp';
import { withPalette } from '@/theme/ThemeRegistry';
import { defaultMaxWidth, headerHeight } from '@/theme/theme';

export const ANNOUNCEMENT_HEIGHT = 34;

const useStyles = withPalette((palette) => {
  const isMobileApp = useIsMobileApp();
  return {
    container: {
      // xs'te header fixed, bu kutu onun yer tutucusu; sm+'da akista oldugu icin
      // icerige gore buyusun — sabit yukseklik altta bos bant birakiyordu.
      height: { xs: headerHeight.xs + ANNOUNCEMENT_HEIGHT, sm: 'auto' },
    },
    banner: {
      justifyContent: 'center',
      height: ANNOUNCEMENT_HEIGHT,
      background: isMobileApp ? palette.bg.main : palette.error.main,
      width: '100vw',
      alignSelf: 'center',
      px: 0,
      overflow: 'hidden',
    },
    bannerInnerContainer: {
      flexDirection: 'row',
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      maxWidth: 'none',
      width: '100vw',
      overflow: 'hidden',
      position: 'relative',
    },
    a: { textDecoration: 'none', color: 'inherit' },
    bannerLink: {
      fontSize: { xs: 12, sm: 13 },
      justifyContent: 'center',
      px: { xs: 2, sm: 3 },
      minHeight: ANNOUNCEMENT_HEIGHT,
      color: isMobileApp ? palette.text.main : palette.error.contrastText,
      whiteSpace: 'nowrap',
      letterSpacing: '0.01em',
      animation: 'banner-fade 4s ease-in-out',
      '@keyframes banner-fade': {
        '0%': { opacity: 0, transform: 'translateY(4px)' },
        '12%': { opacity: 1, transform: 'translateY(0)' },
        '88%': { opacity: 1, transform: 'translateY(0)' },
        '100%': { opacity: 0.85, transform: 'translateY(-2px)' },
      },
      '@media (prefers-reduced-motion: reduce)': {
        animation: 'none',
      },
      '&:hover': {
        backgroundColor: 'transparent',
      },
    },
    innerContainer: {
      zIndex: 1297,
      position: { xs: 'fixed', md: 'relative' },
      top: 0,
      left: 0,
      right: 0,
      height: 'auto',
      background: palette.bg.main,
      transition: 'top 0.2s, box-shadow 0.2s ease-in',
      px: { xs: 1, sm: 3 },
    },
    logo: {
      ...palette.logo,
      width: 150,
      height: 48,
      cursor: 'pointer',
    },
    logoMobile: {
      ...palette.logo,
      width: 112,
      height: 36,
      cursor: 'pointer',
    },
    content: {
      width: '100%',
      alignSelf: 'center',
      maxWidth: defaultMaxWidth,
      gap: { xs: 1, sm: 0.5 },
      py: { xs: 1, sm: 1 },
      position: 'relative',
    },
    primaryBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 2,
    },
    actions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: { sm: 0, lg: 0.5 },
      flexShrink: 0,
    },
    searchPanel: {
      display: { xs: 'none', sm: 'flex' },
      position: 'absolute',
      top: '100%',
      left: 0,
      right: 0,
      zIndex: 1298,
      background: palette.bg.main,
      borderTop: `1px solid ${palette.gray[100] ?? palette.gray[200]}`,
      boxShadow: '0 18px 30px rgba(15, 20, 32, 0.10)',
      py: 2.5,
      px: { sm: 3 },
      animation: 'search-panel-in 0.18s ease',
      '@keyframes search-panel-in': {
        from: { opacity: 0, transform: 'translateY(-8px)' },
        to: { opacity: 1, transform: 'translateY(0)' },
      },
      '@media (prefers-reduced-motion: reduce)': {
        animation: 'none',
      },
    },
    searchPanelInner: {
      width: '100%',
      maxWidth: defaultMaxWidth,
      alignSelf: 'center',
    },
    barSide: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      '& > *': { flexShrink: 0 },
    },
    categoriesToggle: {
      display: { xs: 'none', sm: 'flex', md: 'none' },
      mr: 1,
    },
    inlineLogo: {
      flexShrink: 0,
      alignItems: 'center',
      cursor: 'pointer',
    },
    utilityLinks: {
      display: { xs: 'none', sm: 'flex' },
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      width: '100%',
    },
    utilityLinkInert: {
      cursor: 'default',
      '&:hover': {
        color: `${palette.text.mediumLight} !important`,
      },
    },
    utilityLink: {
      px: 1,
      py: 0.25,
      fontSize: 13,
      fontWeight: 400,
      whiteSpace: 'nowrap',
      color: palette.text.mediumLight,
      '&:hover': {
        color: `${palette.error.main} !important`,
        backgroundColor: 'transparent !important',
      },
    },
    categoryBar: {
      display: { xs: 'none', md: 'flex' },
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 1,
      minWidth: 0,
      overflow: 'hidden',
      gap: 0,
      color: palette.bg.contrastText,
    },
    actionQuiet: {
      color: palette.text.mediumLight,
    },
    actionIcon: {
      width: 48,
      height: 48,
      minWidth: 48,
      p: 0,
      gap: 0,
      justifyContent: 'center',
      borderRadius: 0,
      '& svg': {
        width: 24,
        height: 24,
        strokeWidth: 1.5,
      },
    },
    action: {
      px: { xs: '6px', sm: 1 },
      gap: { xs: 0.5, sm: 1 },
      minWidth: 0,
      color: palette.bg.contrastText,
      '& svg': {
        width: 23,
        height: 23,
      },
    },
    secondaryLinks: {
      flexDirection: 'row',
      alignItems: 'center',
      ml: { sm: 2 },
    },
    shopHeaderLinkQuiet: {
      color: palette.text.mediumLight,
      opacity: 0.72,
    },
    shopHeaderLink: {
      position: 'relative',
      px: { md: 1, lg: 2 },
      py: 1.25,
      fontSize: 15,
      fontWeight: 700,
      textTransform: 'uppercase',
      letterSpacing: '0.01em',
      whiteSpace: 'nowrap',
      color: palette.text.medium,
      transition: 'color 0.15s ease',
      '&::after': {
        content: '""',
        position: 'absolute',
        left: 8,
        right: 8,
        bottom: 0,
        height: 2,
        borderRadius: 1,
        backgroundColor: palette.error.main,
        transform: 'scaleX(0)',
        transformOrigin: 'center',
        transition: 'transform 0.22s cubic-bezier(0.4, 0, 0.2, 1)',
      },
      '&:hover, &.Mui-focusVisible, &:focus, &:active': {
        color: `${palette.error.main} !important`,
        backgroundColor: 'transparent !important',
        outline: 'none',
      },
      '&:hover::after, &:focus-visible::after': {
        transform: 'scaleX(1)',
      },
      '@media (prefers-reduced-motion: reduce)': {
        '&::after': { transition: 'none' },
      },
    },
    megaMenu: {
      display: { xs: 'none', sm: 'block' },
      position: 'absolute',
      top: '100%',
      left: 0,
      right: 0,
      borderRadius: '0 0 12px 12px',
      background: `linear-gradient(180deg, ${palette.bg.main} 0%, ${palette.bg.light} 100%)`,
      boxShadow: '0 22px 38px rgba(15, 20, 32, 0.14)',
      p: { sm: 3.5 },
      zIndex: 2000,
      overflow: 'hidden',
      '&::before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 3,
        background: `linear-gradient(90deg, ${palette.error.light} 0%, ${palette.error.main} 38%, ${palette.error.light} 100%)`,
      },
    },
    megaMenuGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      gap: 2,
    },
    megaMenuGroup: {
      p: 1.5,
      borderRadius: 2,
      backgroundColor: palette.bg.main,
      minHeight: 120,
    },
    megaMenuTitle: {
      mb: 1.25,
      fontWeight: 800,
      fontSize: 16,
      color: palette.text.main,
      letterSpacing: '0.01em',
    },
    megaMenuItem: {
      py: 0.75,
      px: 0.75,
      borderRadius: 1.5,
      cursor: 'pointer',
      color: palette.text.medium,
      fontWeight: 500,
      fontSize: 14,
      userSelect: 'none',
      WebkitTapHighlightColor: 'transparent',
      transition: 'all 0.15s ease',
      '&:hover, &:focus, &:focus-visible, &:active': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
        transform: 'translateX(4px)',
        outline: 'none',
      },
      '&::selection': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
      },
    },
    bottomNavigation: {
      boxShadow: '0 0 5px #00000010',
      zIndex: 1300,
      background: palette.bg.main,
      position: 'fixed',
      right: 0,
      bottom: 0,
      left: 0,
      '& .MuiBottomNavigationAction-label': {
        fontSize: 'min(3vw, 12px)',
        fontWeight: 500,
      },
      '& .Mui-selected': {
        fontWeight: 500,
        fontSize: 'min(3vw, 12px) !important',
      },
    },
    accountMenuItem: {
      flexDirection: 'column',
      background: palette.bg.light,
      color: palette.text.medium,
      py: 1,
      gap: 0.5,
    },
    logoutButton: {
      background: palette.error.light,
      color: palette.error.main,
      width: 'fit-content',
    },
    loginButton: {
      background: palette.success.main,
      color: palette.primary.contrastText,
      width: 'fit-content',
    },
    searchBar: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      maxWidth: { xs: '100%', sm: 260 },
      width: '100%',
      gap: 1.25,
      position: 'relative',
    },
    searchBarWide: {
      maxWidth: 'none',
      justifyContent: 'flex-start',
    },
    searchBarInputWide: {
      '& .MuiOutlinedInput-root': {
        borderRadius: 0,
      },
    },
    searchBarInput: {
      gap: 1,
      '& .MuiOutlinedInput-root': {
        borderRadius: 0,
        minHeight: { xs: 36, sm: 38 },
        px: 0.9,
        py: 0.05,
        border: `1px solid ${palette.gray[300] ?? palette.gray[200]}`,
        background: palette.gray[50] ?? palette.bg.light,
        boxShadow: 'none',
        transition: 'all 0.22s ease',
      },
      '& .MuiOutlinedInput-notchedOutline': {
        border: 'none',
      },
      '& .MuiOutlinedInput-root:hover': {
        borderColor: palette.text.medium,
      },
      '& .MuiOutlinedInput-root.Mui-focused': {
        borderColor: palette.text.main,
        boxShadow: 'none',
      },
      '& .MuiInputBase-input': {
        py: 0.75,
        px: '10px !important',
        fontSize: { xs: 14, sm: 15 },
        fontWeight: 500,
        letterSpacing: '0.01em',
      },
      '& .MuiInputBase-input::placeholder': {
        color: palette.text.light,
        opacity: 1,
        fontWeight: 500,
      },
      '& .MuiIconButton-root': {
        width: { xs: 32, sm: 34 },
        height: { xs: 32, sm: 34 },
        borderRadius: '50%',
        color: palette.text.main,
        background: 'transparent',
        boxShadow: 'none',
        transition: 'none',
        '&:hover': {
          background: 'transparent',
          color: palette.text.main,
          transform: 'none',
        },
      },
      '& .MuiInputAdornment-root': {
        mr: 0.25,
      },
    },
    historyContainer: {
      position: 'absolute',
      top: 'calc(100% + 8px)',
      left: 0,
      width: '100%',
      border: `1px solid ${palette.gray[100]}`,
      backdropFilter: 'blur(10px)',
      backgroundColor: 'rgba(255,255,255,0.94)',
      boxShadow: '0 20px 34px rgba(9, 16, 29, 0.14)',
      px: 1.75,
      py: 1.25,
      zIndex: 1,
      borderRadius: 2.5,
    },
    alert: {
      flexDirection: 'row',
      width: '100vw',
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      background: palette.warning.light,
      color: palette.warning.main,
      height: 56,
      gap: 1,
      px: 2,
      transition: 'height 0.2s',
      overflow: 'hidden',
    },
    backButton: {
      height: 40,
      borderRadius: 2,
      color: 'text.primary',
    },
    loginPrompt: {
      gap: 1.5,
      px: 2,
      py: 1.5,
      borderBottom: `1px solid ${palette.gray[100] ?? palette.gray[200]}`,
      color: palette.text.medium,
    },
  };
});

export default useStyles;
