'use client';

import { useIsMobileApp } from '@/lib/hooks/useIsMobileApp';
import { withPalette } from '@/theme/ThemeRegistry';
import { defaultMaxWidth, headerHeight } from '@/theme/theme';

export const ANNOUNCEMENT_HEIGHT = 34;

const useStyles = withPalette((palette) => {
  const isMobileApp = useIsMobileApp();
  return {
    container: {
      height: { xs: headerHeight.xs + ANNOUNCEMENT_HEIGHT, sm: headerHeight.sm + ANNOUNCEMENT_HEIGHT }
    },
    banner: {
      justifyContent: 'center',
      height: ANNOUNCEMENT_HEIGHT,
      background: isMobileApp ? palette.bg.main : palette.bg.dark,
      width: '100vw',
      alignSelf: 'center',
      px: 0,
      overflow: 'hidden',
    },
    bannerInnerContainer: {
      flexDirection: 'row',
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      maxWidth: 'none',
      width: '100vw',
      overflow: 'hidden',
      position: 'relative',
    },
    a: { textDecoration: 'none', color: 'inherit' },
    bannerMarquee: {
      flexDirection: 'row',
      alignItems: 'center',
      width: 'max-content',
      minWidth: '200%',
      animation: 'banner-marquee var(--banner-marquee-duration, 28s) linear infinite',
      '@keyframes banner-marquee': {
        from: { transform: 'translateX(0)' },
        to: { transform: 'translateX(calc(-1 * var(--banner-marquee-shift, 50%)))' },
      },
    },
    bannerMeasure: {
      position: 'absolute',
      visibility: 'hidden',
      pointerEvents: 'none',
      width: 'max-content',
      whiteSpace: 'nowrap',
      left: 0,
      top: 0,
    },
    bannerLink: {
      fontSize: { xs: 12, sm: 13 },
      gap: 0.5,
      px: { xs: 3, sm: 4 },
      minHeight: ANNOUNCEMENT_HEIGHT,
      color: '#000',
      whiteSpace: 'nowrap',
      flexShrink: 0,
      letterSpacing: '0.01em',
      '&:hover': {
        backgroundColor: 'transparent',
      },
    },
    innerContainer: {
      zIndex: 1297,
      position: { xs: 'fixed', md: 'relative' },
      top: 0,
      left: 0,
      right: 0,
      height: { xs: 'auto', sm: headerHeight.sm + ANNOUNCEMENT_HEIGHT },
      background: palette.bg.main,
      transition: 'top 0.2s, box-shadow 0.2s ease-in',
      px: { xs: 1, sm: 3 },
    },
    logo: {
      ...palette.logo,
      width: 142,
      height: 46,
      cursor: 'pointer',
    },
    content: {
      width: '100%',
      alignSelf: 'center',
      maxWidth: defaultMaxWidth,
      gap: { xs: 1, sm: 2 },
      py: { xs: 1, sm: 2 },
    },
    primaryBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 2,
    },
    actions: { flexDirection: 'row', alignItems: 'center', gap: 0.5 },
    action: {
      px: { xs: '6px', sm: 1 },
      gap: { xs: 0.5, sm: 1 },
      minWidth: 0,
      color: palette.bg.contrastText,
      '& svg': {
        width: 23,
        height: 23,
      },
    },
    secondaryBar: {
      display: { xs: 'none', sm: 'flex' },
      flexDirection: 'row',
      alignItems: 'center',
      color: palette.text.medium,
      justifyContent: 'center',
      width: { xs: '100vw', sm: '100%' },
      alignSelf: { xs: 'center' },
      gap: 1,
      position: 'relative',
    },
    shopHeaderLinks: {
      flexDirection: 'row',
      alignItems: 'center',
      overflow: { xs: 'scroll', sm: 'hidden' },
      flexWrap: { sm: 'wrap' },
      height: 28,
      scrollbarWidth: 'none',
      MsOverflowStyle: 'none',
      width: '100%',
      '&::-webkit-scrollbar': { display: 'none' },
      px: { xs: 1, sm: 0 },
      color: palette.bg.contrastText,
    },
    shopHeaderLink: {
      fontWeight: 500,
      color: palette.text.medium,
      '&:hover': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
      },
      '&.Mui-focusVisible, &:focus, &:active': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
        outline: 'none',
      },
      '&.Mui-selected': {
        fontWeight: 500,
        color: palette.error.dark,
      },
    },
    megaMenu: {
      position: 'absolute',
      top: 'calc(100% + 10px)',
      left: '50%',
      transform: 'translateX(-50%)',
      width: 'min(100%, 1220px)',
      borderRadius: 3,
      background: `linear-gradient(180deg, ${palette.bg.main} 0%, ${palette.bg.light} 100%)`,
      boxShadow: '0 22px 38px rgba(15, 20, 32, 0.14)',
      p: { sm: 3.5 },
      zIndex: 2000,
      overflow: 'hidden',
      '&::before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 3,
        background: `linear-gradient(90deg, ${palette.error.light} 0%, ${palette.error.main} 38%, ${palette.error.light} 100%)`,
      },
    },
    megaMenuGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      gap: 2,
    },
    megaMenuGroup: {
      p: 1.5,
      borderRadius: 2,
      backgroundColor: palette.bg.main,
      minHeight: 120,
    },
    megaMenuTitle: {
      mb: 1.25,
      fontWeight: 800,
      fontSize: 16,
      color: palette.text.main,
      letterSpacing: '0.01em',
    },
    megaMenuItem: {
      py: 0.75,
      px: 0.75,
      borderRadius: 1.5,
      cursor: 'pointer',
      color: palette.text.medium,
      fontWeight: 500,
      fontSize: 14,
      userSelect: 'none',
      WebkitTapHighlightColor: 'transparent',
      transition: 'all 0.15s ease',
      '&:hover, &:focus, &:focus-visible, &:active': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
        transform: 'translateX(4px)',
        outline: 'none',
      },
      '&::selection': {
        color: `${palette.error.main} !important`,
        backgroundColor: `${palette.error.light} !important`,
      },
    },
    bottomNavigation: {
      boxShadow: '0 0 5px #00000010',
      zIndex: 1300,
      background: palette.bg.main,
      position: 'fixed',
      right: 0,
      bottom: 0,
      left: 0,
      '& .MuiBottomNavigationAction-label': {
        fontSize: 'min(3vw, 12px)',
        fontWeight: 500,
      },
      '& .Mui-selected': {
        fontWeight: 500,
        fontSize: 'min(3vw, 12px) !important',
      },
    },
    accountMenuItem: {
      flexDirection: 'column',
      background: palette.bg.light,
      color: palette.text.medium,
      py: 1,
      gap: 0.5,
    },
    logoutButton: {
      background: palette.error.light,
      color: palette.error.main,
      width: 'fit-content',
    },
    loginButton: {
      background: palette.success.main,
      color: palette.primary.contrastText,
      width: 'fit-content',
    },
    searchBar: {
      flexDirection: 'row',
      justifyContent: 'center',
      maxWidth: 620,
      width: '100%',
      gap: 1.25,
      position: 'relative',
    },
    searchBarInput: {
      gap: 1,
      '& .MuiOutlinedInput-root': {
        borderRadius: 999,
        minHeight: { xs: 36, sm: 40 },
        px: 0.9,
        py: 0.05,
        border: `1px solid ${palette.gray[300] ?? palette.gray[200]}`,
        background: `linear-gradient(180deg, ${palette.bg.main} 0%, ${palette.gray[50] ?? palette.bg.light} 100%)`,
        boxShadow: '0 10px 22px rgba(24, 29, 41, 0.07)',
        transition: 'all 0.22s ease',
      },
      '& .MuiOutlinedInput-notchedOutline': {
        border: 'none',
      },
      '& .MuiOutlinedInput-root:hover': {
        borderColor: palette.text.medium,
        boxShadow: '0 12px 26px rgba(24, 29, 41, 0.1)',
      },
      '& .MuiOutlinedInput-root.Mui-focused': {
        borderColor: palette.error.main,
        boxShadow: `0 0 0 2px ${palette.error.light}`,
        transform: 'translateY(-1px)',
      },
      '& .MuiInputBase-input': {
        py: 0.75,
        px: '10px !important',
        fontSize: { xs: 14, sm: 15 },
        fontWeight: 500,
        letterSpacing: '0.01em',
      },
      '& .MuiInputBase-input::placeholder': {
        color: palette.text.light,
        opacity: 1,
        fontWeight: 500,
      },
      '& .MuiIconButton-root': {
        width: { xs: 32, sm: 34 },
        height: { xs: 32, sm: 34 },
        borderRadius: '50%',
        color: palette.text.main,
        background: 'transparent',
        boxShadow: 'none',
        transition: 'none',
        '&:hover': {
          background: 'transparent',
          color: palette.text.main,
          transform: 'none',
        },
      },
      '& .MuiInputAdornment-root': {
        mr: 0.25,
      },
    },
    historyContainer: {
      position: 'absolute',
      top: 'calc(100% + 8px)',
      left: 0,
      width: '100%',
      border: `1px solid ${palette.gray[100]}`,
      backdropFilter: 'blur(10px)',
      backgroundColor: 'rgba(255,255,255,0.94)',
      boxShadow: '0 20px 34px rgba(9, 16, 29, 0.14)',
      px: 1.75,
      py: 1.25,
      zIndex: 1,
      borderRadius: 2.5,
    },
    alert: {
      flexDirection: 'row',
      width: '100vw',
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      background: palette.warning.light,
      color: palette.warning.main,
      height: 56,
      gap: 1,
      px: 2,
      transition: 'height 0.2s',
      overflow: 'hidden',
    },
    backButton: {
      height: 40,
      borderRadius: 2,
      color: 'text.primary',
    },
    loginPrompt: {
      gap: 1.5,
      px: 2,
      py: 1.5,
      borderBottom: `1px solid ${palette.gray[100] ?? palette.gray[200]}`,
      color: palette.text.medium,
    },
  };
});

export default useStyles;
