import { CSSProperties } from 'react';

const styles = {
  header: {
    px: { xs: 2, sm: 2.5 },
    py: 1.75,
    border: '1px solid',
    borderColor: 'gray.200',
    borderRadius: '14px',
    bgcolor: 'white.main',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: 'text.main',
  },
  headerCount: {
    fontSize: 13,
    fontWeight: 600,
    color: 'text.medium',
  },
  loadingState: {
    border: '1px solid',
    borderColor: 'gray.200',
    borderRadius: '12px',
    bgcolor: 'white.main',
    minHeight: 140,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
  },
  loadingText: {
    fontSize: 14,
    color: 'text.medium',
    fontWeight: 600,
  },
  emptyState: {
    border: '1px solid',
    borderColor: 'gray.200',
    borderRadius: '12px',
    bgcolor: 'white.main',
    px: { xs: 2, sm: 2.5 },
    py: { xs: 2.5, sm: 3 },
    gap: 0.8,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: 'text.main',
  },
  emptyDescription: {
    fontSize: 14,
    color: 'text.medium',
    lineHeight: 1.5,
  },
  itemCard: {
    p: { xs: 1.25, sm: 1.5 },
    border: '1px solid',
    borderColor: 'gray.200',
    borderRadius: '12px',
    bgcolor: 'bg.light',
    flexDirection: { xs: 'column', sm: 'row' },
    alignItems: { xs: 'stretch', sm: 'center' },
    justifyContent: 'space-between',
    gap: 1.2,
  },
  imageWrap: {
    width: 56,
    height: 56,
    borderRadius: '10px',
    bgcolor: 'white.main',
    border: '1px solid',
    borderColor: 'gray.200',
    overflow: 'hidden',
    flexShrink: 0,
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  } as CSSProperties,
  productName: {
    fontSize: 14,
    fontWeight: 600,
    color: 'text.main',
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  price: {
    fontSize: 14,
    fontWeight: 700,
    color: 'text.main',
    mt: 0.4,
  },
  viewButton: {
    borderRadius: '8px',
    textTransform: 'none',
    fontWeight: 700,
  },
  removeButton: {
    borderRadius: '8px',
    textTransform: 'none',
    color: 'error.main',
    fontWeight: 700,
  },
};

export default styles;
