import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  container: {
    flexDirection: { xs: 'column', sm: 'row' },
    width: '100%',
    gap: { xs: 2, sm: 3, md: 4 },
  },
  navigation: {
    height: 'fit-content',
    width: { sm: 232, md: 240, lg: 248 },
    flexShrink: 0,
    p: 1,
    gap: 1,
    borderRadius: '16px',
    border: 'none',
    bgcolor: 'transparent',
    position: 'static' as const,
  },
  accountIdentity: {
    border: `1px solid ${palette.gray[200]}`,
    borderRadius: '12px',
    px: 1.25,
    py: 1,
    bgcolor: palette.white.main,
  },
  accountName: {
    fontSize: 17,
    fontWeight: 600,
    lineHeight: 1.2,
    color: palette.text.main,
  },
  groupCard: {
    border: `1px solid ${palette.gray[200]}`,
    borderRadius: '12px',
    p: 0.75,
    gap: 0.5,
    bgcolor: palette.white.main,
  },
  groupTitle: {
    px: 0.5,
    py: 0.25,
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.2,
    color: palette.text.main,
    letterSpacing: -0.1,
  },
  menuItem: {
    borderRadius: '9px',
    minHeight: 38,
    fontSize: 13,
    fontWeight: 400,
    color: palette.text.mediumLight,
    py: 0.5,
    px: 0.75,
    gap: 0.9,
    transition: 'all 0.15s ease',
    '&:hover': {
      bgcolor: palette.bg.dark,
      color: palette.text.main,
    },
    '&.Mui-selected': {
      bgcolor: palette.bg.dark,
      color: palette.text.main,
      fontWeight: 500,
      '&:hover': {
        bgcolor: palette.bg.dark,
      },
    },
    '&.Mui-disabled': {
      opacity: 1,
      color: palette.text.mediumLight,
    },
  },
  menuItemLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 1.2,
    color: 'inherit',
  },
  menuItemIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 26,
    height: 26,
    borderRadius: '7px',
    flexShrink: 0,
    border: `1px solid ${palette.gray[200]}`,
    bgcolor: palette.white.main,
  },
  menuBadge: {
    minWidth: 20,
    height: 20,
    px: 0.5,
    borderRadius: '999px',
    display: 'grid',
    placeItems: 'center',
    fontSize: 11,
    fontWeight: 800,
    color: palette.text.main,
    bgcolor: palette.gray[100],
  },
  divider: {
    my: 0.75,
    mx: 0.25,
    borderColor: palette.gray[200],
  },
  /* Unauthenticated state */
  authContainer: {
    textAlign: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    py: { xs: 6, sm: 10 },
    gap: 3,
  },
  authIconBox: {
    width: 88,
    height: 88,
    borderRadius: '22px',
    background: `linear-gradient(135deg, ${palette.bg.dark} 0%, ${palette.gray[100]} 100%)`,
    display: 'grid',
    placeItems: 'center',
  },
  authTitle: {
    fontSize: { xs: 20, sm: 24 },
    fontWeight: 800,
    letterSpacing: -0.3,
    color: palette.text.main,
  },
  authDescription: {
    fontSize: { xs: 15, sm: 16 },
    fontWeight: 500,
    color: palette.text.mediumLight,
    maxWidth: 400,
    lineHeight: 1.6,
  },
  authActions: {
    direction: 'row',
    gap: 1,
    width: '100%',
    maxWidth: 380,
  },
}));

export default useStyles;
