import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  fabDock: {
    position: 'fixed',
    right: { xs: 18, sm: 28 },
    bottom: { xs: 18, sm: 28 },
    zIndex: 1300,
  },
  fab: {
    height: 54,
    minHeight: 54,
    minWidth: 132,
    padding: '0 18px 0 14px',
    borderRadius: 999,
    border: '1px solid',
    borderColor: 'rgba(255,255,255,0.12)',
    color: '#FFFFFF',
    background: palette.primary?.gradient ?? 'linear-gradient(180deg, #000000 0%, #1C1C1E 100%)',
    boxShadow: '0 12px 28px rgba(17, 17, 17, 0.18), inset 0 1px 0 rgba(255,255,255,0.08), inset 0 -8px 16px rgba(0,0,0,0.18)',
    transition: 'transform 0.22s ease, box-shadow 0.22s ease, border-color 0.22s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.8,
    overflow: 'hidden',
    '&:hover': {
      transform: 'translateY(-1px)',
      borderColor: 'rgba(255,255,255,0.22)',
      boxShadow: '0 16px 36px rgba(17, 17, 17, 0.24), inset 0 1px 0 rgba(255,255,255,0.08), inset 0 -8px 16px rgba(0,0,0,0.18)',
    },
  },
  fabIconWrap: {
    display: 'grid',
    placeItems: 'center',
    width: 26,
    height: 26,
    flexShrink: 0,
    color: '#FFFFFF',
  },
  fabText: {
    fontSize: 15,
    fontWeight: 600,
    lineHeight: 1,
    letterSpacing: '-0.01em',
    color: '#FFFFFF',
  },
  fabTooltip: {
    backgroundColor: '#111111',
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    borderRadius: 999,
    px: 1.2,
    py: 0.75,
    boxShadow: '0 14px 30px rgba(17, 24, 39, 0.18)',
  },
  fabTooltipArrow: {
    color: '#171717',
  },
  entryCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.75,
    p: 1.9,
    borderRadius: 3,
    border: '1px solid',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
  },
  entrySidebar: {
    mb: 2,
    background: 'linear-gradient(180deg, rgba(255,255,255,0.96), rgba(249,249,249,0.92))',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    boxShadow: '0 12px 24px rgba(17, 24, 39, 0.04)',
    '&:hover': {
      transform: 'translateY(-1px)',
      borderColor: '#D7C5C1',
      boxShadow: '0 16px 30px rgba(17, 24, 39, 0.06)',
    },
  },
  entryFaq: {
    padding: { xs: 2.1, sm: 2.4 },
    background: 'linear-gradient(180deg, rgba(255,255,255,0.96), rgba(252,248,247,0.92))',
    borderColor: '#E4D7D4',
    boxShadow: '0 14px 28px rgba(17, 24, 39, 0.05)',
  },
  entryBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.5,
    alignSelf: 'flex-start',
    px: 1,
    py: 0.42,
    borderRadius: 999,
    backgroundColor: 'rgba(198, 61, 47, 0.09)',
    color: '#B3392B',
  },
  entryBadgeText: {
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1,
  },
  entryIconWrap: {
    width: 46,
    height: 46,
    flexShrink: 0,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    backgroundColor: '#171717',
    color: '#FFFFFF',
    boxShadow: '0 10px 18px rgba(0,0,0,0.14)',
  },
  entryTitle: {
    fontSize: { xs: 18, sm: 20 },
    fontWeight: 700,
    lineHeight: 1.2,
    color: palette.text.main,
  },
  entryDescription: {
    fontSize: { xs: 14, sm: 15 },
    lineHeight: 1.55,
    color: palette.text.secondary,
  },
  entryPrimaryButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    px: 1.6,
    py: 0.9,
    textTransform: 'none',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #171717 0%, #2A2A2A 100%)',
    color: '#FFFFFF',
    boxShadow: 'none',
    '&:hover': {
      background: 'linear-gradient(135deg, #B3392B 0%, #8F231A 100%)',
      boxShadow: 'none',
    },
  },
  entrySecondaryButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    px: 1.8,
    py: 1,
    textTransform: 'none',
    fontWeight: 700,
    fontSize: 14,
    borderColor: '#D8C8C5',
    color: palette.text.main,
    '&:hover': {
      borderColor: '#B3392B',
      backgroundColor: 'rgba(198, 61, 47, 0.05)',
    },
  },
  entryInlineSidebar: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.6,
    alignSelf: 'flex-start',
    padding: 0,
    marginTop: 0.5,
    border: 'none',
    background: 'transparent',
    color: palette.text.main,
    cursor: 'pointer',
  },
  entryInlineFaq: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.6,
    alignSelf: 'flex-start',
    padding: 0,
    marginTop: 1,
    border: 'none',
    background: 'transparent',
    color: palette.text.main,
    cursor: 'pointer',
  },
  entryInlineText: {
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.4,
    color: palette.text.main,
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
  },
  panel: {
    position: 'fixed',
    right: { xs: 0, sm: 28 },
    bottom: { xs: 0, sm: 96 },
    zIndex: 1301,
    width: { xs: '100%', sm: 392 },
    height: { xs: '100dvh', sm: 'min(72dvh, 620px)' },
    maxHeight: { xs: '100dvh', sm: 620 },
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRadius: { xs: 0, sm: 2 },
    border: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    background: `linear-gradient(180deg, ${palette.bg.main} 0%, ${palette.bg.light ?? '#F6F6F6'} 100%)`,
    boxShadow: '0 30px 80px rgba(17, 24, 39, 0.18)',
    backdropFilter: 'blur(20px)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    px: 2.25,
    py: 1.75,
    borderBottom: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    background: 'linear-gradient(135deg, #161616 0%, #252525 100%)',
    color: '#FFFFFF',
  },
  headerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    minWidth: 0,
  },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    border: '1px solid rgba(255,255,255,0.18)',
    flexShrink: 0,
  },
  closeButton: {
    color: 'inherit',
    backgroundColor: 'rgba(255,255,255,0.1)',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
  },
  content: {
    flex: 1,
    minHeight: 0,
    px: 1.5,
    py: 1.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.25,
    overflowY: 'auto',
    scrollbarWidth: 'thin',
  },
  introCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  suggestions: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 1,
  },
  suggestionButton: {
    minHeight: 58,
    justifyContent: 'center',
    px: 2.5,
    py: 1,
    borderRadius: '18px',
    textTransform: 'none',
    fontSize: { xs: 16, sm: 18 },
    fontWeight: 500,
    border: '1px solid',
    borderColor: palette.gray?.[500] ?? '#6E6E73',
    color: palette.primary?.main ?? '#111111',
    backgroundColor: 'transparent',
    '&:hover': {
      borderColor: palette.accentRed?.main ?? '#C1121F',
      color: palette.accentRed?.main ?? '#C1121F',
      backgroundColor: palette.accentRed?.light ?? '#FDEBEC',
    },
  },
  messageRow: {
    display: 'flex',
  },
  messageGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.5,
    maxWidth: '85%',
  },
  userRow: {
    justifyContent: 'flex-end',
  },
  assistantRow: {
    justifyContent: 'flex-start',
  },
  messageMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    fontSize: 12,
    lineHeight: 1,
    color: palette.text.secondary,
  },
  userMeta: {
    justifyContent: 'flex-end',
  },
  assistantMeta: {
    justifyContent: 'flex-start',
  },
  messageAuthor: {
    fontSize: 12,
    fontWeight: 500,
    color: palette.text.secondary,
  },
  messageTime: {
    fontSize: 12,
    color: palette.text.secondary,
  },
  userBubble: {
    px: 1.5,
    py: 1.2,
    borderRadius: '18px 18px 6px 18px',
    color: '#FFFFFF',
    background: `linear-gradient(135deg, ${palette.primary.main} 0%, ${palette.primary.dark ?? palette.primary.main} 100%)`,
    boxShadow: '0 10px 24px rgba(0,0,0,0.12)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  assistantBubble: {
    px: 1.5,
    py: 1.2,
    borderRadius: '18px 18px 18px 6px',
    color: palette.text.main,
    backgroundColor: 'rgba(255,255,255,0.9)',
    border: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    boxShadow: '0 12px 24px rgba(17, 24, 39, 0.05)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  typingCaret: {
    display: 'inline-block',
    width: 8,
    height: '1em',
    marginLeft: '2px',
    verticalAlign: 'text-bottom',
    borderRadius: 999,
    backgroundColor: 'currentColor',
    animation: 'productQaCaretBlink 0.9s steps(1) infinite',
    '@keyframes productQaCaretBlink': {
      '0%, 49%': {
        opacity: 1,
      },
      '50%, 100%': {
        opacity: 0,
      },
    },
  },
  typingDots: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.5,
    minHeight: 18,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: palette.text.secondary,
    opacity: 0.35,
    animation: 'productQaTypingDots 1.2s infinite ease-in-out',
    '&:nth-of-type(2)': {
      animationDelay: '0.18s',
    },
    '&:nth-of-type(3)': {
      animationDelay: '0.36s',
    },
    '@keyframes productQaTypingDots': {
      '0%, 80%, 100%': {
        transform: 'translateY(0)',
        opacity: 0.35,
      },
      '40%': {
        transform: 'translateY(-3px)',
        opacity: 1,
      },
    },
  },
  composer: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 1,
    px: 1.5,
    py: 1.5,
    borderTop: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    backgroundColor: 'rgba(255,255,255,0.82)',
    backdropFilter: 'blur(16px)',
  },
  textarea: {
    flex: 1,
    minHeight: 48,
    maxHeight: 140,
    padding: '12px 14px',
    borderRadius: 18,
    border: '1px solid',
    borderColor: palette.gray?.[300] ?? '#D0D0D0',
    backgroundColor: '#FFFFFF',
    color: palette.text.main,
    font: 'inherit',
    lineHeight: 1.45,
    resize: 'none',
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    '&:focus': {
      borderColor: '#C63D2F',
      boxShadow: '0 0 0 4px rgba(198, 61, 47, 0.14)',
    },
    '&::placeholder': {
      color: palette.text.secondary,
      opacity: 1,
    },
    '&:disabled': {
      backgroundColor: palette.bg.light ?? '#F5F5F5',
    },
  },
  sendButton: {
    width: 44,
    height: 44,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #C63D2F 0%, #8F231A 100%)',
    boxShadow: '0 10px 20px rgba(143, 35, 26, 0.18)',
    '&:hover': {
      background: 'linear-gradient(135deg, #8F231A 0%, #C63D2F 100%)',
    },
    '&.Mui-disabled': {
      color: '#FFFFFF',
      opacity: 0.5,
    },
  },
}));

export default useStyles;
