const styles = {
  wrapper: {
    borderRadius: '12px',
    border: '1px solid',
    borderColor: 'gray.100',
    bgcolor: 'white.main',
    overflow: 'hidden',
  },
  header: {
    px: { xs: 2, sm: 2.5 },
    py: 1.5,
    borderBottom: '1px solid',
    borderColor: 'gray.100',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLabel: {
    fontSize: 13,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0,
    color: 'text.medium',
  },
  headerCount: {
    fontSize: 13,
    fontWeight: 700,
    color: 'text.mediumLight',
  },
  cardBody: {
    py: 0,
    px: 0,
  },
  address: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 1.5,
    px: { xs: 2, sm: 2.5 },
    py: 1.5,
    transition: 'background-color 0.15s ease',
    '&:hover': {
      bgcolor: 'bg.light',
    },
  },
  addressInfo: {
    flex: 1,
    overflow: 'hidden',
    gap: 0.25,
  },
  addressName: {
    fontSize: 14,
    fontWeight: 600,
    color: 'text.main',
    lineHeight: 1.3,
    whiteSpace: 'nowrap',
  },
  addressLine: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
    fontSize: 13,
    fontWeight: 500,
    color: 'text.mediumLight',
    lineHeight: 1.4,
    wordBreak: 'break-all',
  },
  addressActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 0.25,
  },
  iconButton: {
    width: 30,
    height: 30,
    borderRadius: '8px',
  },
  divider: {
    mx: 2.5,
    borderColor: 'gray.100',
  },
  addButton: {
    mx: { xs: 2, sm: 2.5 },
    my: 1.5,
    borderRadius: '10px',
    borderStyle: 'dashed',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: 13,
  },
};

export default styles;
