const styles = {
  container: {
    gap: 1.5,
  },
  header: {
    px: { xs: 2, sm: 2.5 },
    py: 1.75,
    border: '1px solid',
    borderColor: 'gray.200',
    borderRadius: '14px',
    bgcolor: 'white.main',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLabel: {
    fontSize: 18,
    fontWeight: 600,
    color: 'text.main',
  },
  headerAddButton: {
    borderRadius: '10px',
    textTransform: 'none',
    fontSize: 16,
    fontWeight: 600,
    px: 0.75,
    minHeight: 38,
  },
  cardBody: {
    py: 0,
    px: 0,
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))', md: 'repeat(3, minmax(0, 1fr))' },
    gap: 1.25,
  },
  cardItem: {
    minWidth: 0,
  },
  address: {
    flexDirection: 'column',
    alignItems: 'stretch',
    width: '100%',
    gap: 0.75,
    p: { xs: 1.25, sm: 1.5 },
    borderRadius: '12px',
    border: '1px solid',
    borderColor: 'gray.200',
    bgcolor: 'bg.light',
  },
  addressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressInfo: {
    gap: 0.35,
  },
  addressName: {
    fontSize: 15,
    fontWeight: 600,
    color: 'text.main',
    lineHeight: 1.35,
  },
  defaultBadge: {
    width: 18,
    height: 18,
    borderRadius: '999px',
    bgcolor: 'tertiary.main',
    color: 'white.main',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  contactName: {
    fontSize: 13,
    color: 'text.medium',
    lineHeight: 1.45,
  },
  addressLine: {
    fontSize: 13,
    fontWeight: 400,
    color: 'text.medium',
    lineHeight: 1.45,
    wordBreak: 'break-word',
  },
  locationLine: {
    fontSize: 13,
    fontWeight: 400,
    color: 'text.medium',
    lineHeight: 1.45,
  },
  phoneLine: {
    mt: 0.25,
    fontSize: 13,
    fontWeight: 500,
    color: 'text.main',
    lineHeight: 1.4,
  },
  addressActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    mt: 0.25,
  },
  deleteIconButton: {
    width: 34,
    height: 34,
    borderRadius: '8px',
    border: '1px solid',
    borderColor: 'gray.200',
    bgcolor: 'white.main',
    color: 'error.main',
  },
  editButton: {
    borderRadius: '8px',
    textTransform: 'none',
    fontSize: 13,
    px: 1.25,
    height: 34,
  },
  editButtonLabel: {
    fontSize: 13,
    fontWeight: 500,
  },
};

export default styles;
