import { withPalette } from '@/theme/ThemeRegistry';
import { defaultMaxWidth } from '@/theme/theme';

const useStyles = withPalette((palette) => ({
  container: {
    width: '100vw',
    mt: 10,
    px: { xs: 2, sm: 3 },
    pb: { xs: 16, sm: 8 },
    pt: { xs: 4, sm: 5 },
    backgroundColor: palette.primaryDark.dark,
    color: palette.white.main,
  },
  innerContainer: { width: '100%', maxWidth: defaultMaxWidth, alignSelf: 'center', gap: 2 },
  logo: { ...palette.logoWhite, cursor: 'pointer' },
  etbisInfoCard: {
    position: 'relative',
    overflow: 'hidden',
    mt: { md: 0.5 },
    maxWidth: 280,
    minWidth: { md: 250 },
    p: { xs: 1.5, sm: 1.75 },
    borderRadius: 2.5,
    border: `1px solid ${palette.gray[700]}`,
    background: 'linear-gradient(180deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.02) 100%)',
    backdropFilter: 'blur(4px)',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.06), 0 8px 20px rgba(0,0,0,0.2)',
    display: 'flex',
    flexDirection: 'column',
    gap: 0.85,
  },
  etbisInfoBadge: {
    width: 'fit-content',
    py: 0.6,
    borderRadius: 99,
    color: palette.white.main,
    lineHeight: 1,
  },
  etbisInfoBadgeText: {
    color: palette.white.main,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.45,
    lineHeight: 1,
  },
  etbisInfoTitle: {
    color: palette.white.main,
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: 0.15,
    lineHeight: 1.3,
  },
  etbisInfoBody: {
    color: palette.gray[200],
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: 0.1,
    lineHeight: 1.45,
  },
  etbisInfoCta: {
    mt: 0.4,
    px: 1.1,
    py: 0.8,
    borderRadius: 1.5,
    border: `1px solid ${palette.gray[500]}`,
    backgroundColor: 'rgba(255,255,255,0.04)',
    color: palette.white.main,
    transition: 'border-color 0.2s, background-color 0.2s, transform 0.2s',
    '&:hover': {
      borderColor: palette.gray[300],
      backgroundColor: 'rgba(255,255,255,0.08)',
      transform: 'translateY(-1px)',
    },
  },
  etbisInfoCtaText: {
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.2,
    lineHeight: 1.2,
  },
  socials: { flexDirection: 'row', gap: 1.25 },
  linkGroupTitle: {
    color: palette.white.main,
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 0.3,
    lineHeight: '22px',
  },
  mobileLinkGroupCard: {
    bgcolor: 'transparent',
    borderRadius: 0,
    borderBottom: '1px solid',
    borderColor: 'rgba(255,255,255,0.1)',
    '& .MuiAccordion-root': { bgcolor: 'transparent' },
    '& .MuiAccordionDetails-root': { borderTop: 'none' },
    header: {
      px: 0,
      py: 1,
      textTransform: 'none',
      color: 'inherit',
    },
  },
  bottomBar: {
    width: '100%',
    mt: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    color: palette.gray[300],
  },
  item: {
    display: 'flex',
    width: 'fit-content',
    fontSize: 14,
    fontWeight: 500,
    lineHeight: '20px',
    color: palette.gray[200],
    textDecoration: 'none',
  },
  markdownOptions: {
    p: {
      sx: {
        fontWeight: 400,
        fontSize: { xs: 13, sm: 14 },
        lineHeight: { xs: 1.65, sm: 1.7 },
        color: palette.gray[300],
      },
    },
  },
  vendors: { flexDirection: 'row', gap: 1.5, justifyContent: 'center', pt: 2, flexWrap: 'wrap' },
}));

export default useStyles;
