import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  panel: {
    position: 'fixed',
    right: { xs: 0, sm: 28 },
    bottom: { xs: 0, sm: 96 },
    zIndex: 1301,
    width: { xs: '100%', sm: 392 },
    height: { xs: '100dvh', sm: 'min(72dvh, 620px)' },
    maxHeight: { xs: '100dvh', sm: 620 },
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRadius: { xs: 0, sm: 2 },
    border: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    background: `linear-gradient(180deg, ${palette.bg.main} 0%, ${palette.bg.light ?? '#F6F6F6'} 100%)`,
    boxShadow: '0 30px 80px rgba(17, 24, 39, 0.18)',
    backdropFilter: 'blur(20px)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    px: 2.25,
    py: 1.75,
    borderBottom: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    background: 'linear-gradient(135deg, #161616 0%, #252525 100%)',
    color: '#FFFFFF',
  },
  headerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    minWidth: 0,
  },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    border: '1px solid rgba(255,255,255,0.18)',
    flexShrink: 0,
  },
  closeButton: {
    color: 'inherit',
    backgroundColor: 'rgba(255,255,255,0.1)',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
  },
  content: {
    flex: 1,
    minHeight: 0,
    px: 1.5,
    py: 1.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.25,
    overflowY: 'auto',
    scrollbarWidth: 'thin',
  },
  introCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  suggestions: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 1,
  },
  suggestionButton: {
    minHeight: 58,
    justifyContent: 'center',
    px: 2.5,
    py: 1,
    borderRadius: '18px',
    textTransform: 'none',
    fontSize: { xs: 16, sm: 18 },
    fontWeight: 500,
    border: '1px solid',
    borderColor: palette.gray?.[500] ?? '#6E6E73',
    color: palette.primary?.main ?? '#111111',
    backgroundColor: 'transparent',
    '&:hover': {
      borderColor: palette.accentRed?.main ?? '#C1121F',
      color: palette.accentRed?.main ?? '#C1121F',
      backgroundColor: palette.accentRed?.light ?? '#FDEBEC',
    },
  },
  messageRow: {
    display: 'flex',
  },
  messageGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0.5,
    maxWidth: '85%',
  },
  userRow: {
    justifyContent: 'flex-end',
  },
  assistantRow: {
    justifyContent: 'flex-start',
  },
  messageMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    fontSize: 12,
    lineHeight: 1,
    color: palette.text.secondary,
  },
  userMeta: {
    justifyContent: 'flex-end',
  },
  assistantMeta: {
    justifyContent: 'flex-start',
  },
  messageAuthor: {
    fontSize: 12,
    fontWeight: 500,
    color: palette.text.secondary,
  },
  messageTime: {
    fontSize: 12,
    color: palette.text.secondary,
  },
  userBubble: {
    px: 1.5,
    py: 1.2,
    borderRadius: '18px 18px 6px 18px',
    color: '#FFFFFF',
    background: `linear-gradient(135deg, ${palette.primary.main} 0%, ${palette.primary.dark ?? palette.primary.main} 100%)`,
    boxShadow: '0 10px 24px rgba(0,0,0,0.12)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  assistantBubble: {
    px: 1.5,
    py: 1.2,
    borderRadius: '18px 18px 18px 6px',
    color: palette.text.main,
    backgroundColor: 'rgba(255,255,255,0.9)',
    border: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    boxShadow: '0 12px 24px rgba(17, 24, 39, 0.05)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  typingCaret: {
    display: 'inline-block',
    width: 8,
    height: '1em',
    marginLeft: '2px',
    verticalAlign: 'text-bottom',
    borderRadius: 999,
    backgroundColor: 'currentColor',
    animation: 'productQaCaretBlink 0.9s steps(1) infinite',
    '@keyframes productQaCaretBlink': {
      '0%, 49%': { opacity: 1 },
      '50%, 100%': { opacity: 0 },
    },
  },
  typingDots: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.5,
    minHeight: 18,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: palette.text.secondary,
    opacity: 0.35,
    animation: 'productQaTypingDots 1.2s infinite ease-in-out',
    '&:nth-of-type(2)': { animationDelay: '0.18s' },
    '&:nth-of-type(3)': { animationDelay: '0.36s' },
    '@keyframes productQaTypingDots': {
      '0%, 80%, 100%': { transform: 'translateY(0)', opacity: 0.35 },
      '40%': { transform: 'translateY(-3px)', opacity: 1 },
    },
  },
  composer: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 1,
    px: 1.5,
    py: 1.5,
    borderTop: '1px solid',
    borderColor: palette.gray?.[200] ?? '#E8E8E8',
    backgroundColor: 'rgba(255,255,255,0.82)',
    backdropFilter: 'blur(16px)',
  },
  textarea: {
    flex: 1,
    minHeight: 48,
    maxHeight: 140,
    padding: '12px 14px',
    borderRadius: 18,
    border: '1px solid',
    borderColor: palette.gray?.[300] ?? '#D0D0D0',
    backgroundColor: '#FFFFFF',
    color: palette.text.main,
    font: 'inherit',
    lineHeight: 1.45,
    resize: 'none',
    outline: 'none',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    '&:focus': {
      borderColor: '#C63D2F',
      boxShadow: '0 0 0 4px rgba(198, 61, 47, 0.14)',
    },
    '&::placeholder': {
      color: palette.text.secondary,
      opacity: 1,
    },
    '&:disabled': {
      backgroundColor: palette.bg.light ?? '#F5F5F5',
    },
  },
  sendButton: {
    width: 44,
    height: 44,
    color: '#FFFFFF',
    background: 'linear-gradient(135deg, #C63D2F 0%, #8F231A 100%)',
    boxShadow: '0 10px 20px rgba(143, 35, 26, 0.18)',
    '&:hover': {
      background: 'linear-gradient(135deg, #8F231A 0%, #C63D2F 100%)',
    },
    '&.Mui-disabled': {
      color: '#FFFFFF',
      opacity: 0.5,
    },
  },
}));

export default useStyles;
