const brands = [
  'victoria secret',
  'victorias secret',
  'zara',
  'stradivarius',
  'ipekyol & twist',
  'ipekyol and twist',
  'ipekyol twist',
  'mavi',
  'penti',
  'oysho',
  'bershka',
  'elle',
  'adl',
  'pull & bear',
  'pull and bear',
  'pull bear',
  'gap',
  'koton',
  'defacto',
  'network',
  'marks&spencer',
  'marks and spencer',
  'marks spencer',
  'puma',
  'tommy hilfiger',
  'pull&bear',
  'pull and bear',
  'pull bear',
  'trendyol curve',
  'lc waikiki',
  'us polo',
  'guess',
  'suwen',
  'benetton',
  'fabrika',
  'calvin klein',
  'under armour',
  'lacoste',
  'massimo dutti',
  'columbia',
  'twist',
  'ipekyol',
  'jack wolfskin',
  'wrangler',
  'decathlon',
  'lee cooper',
  'jack jones',
  'armani exchange',
  'emporio armani',
  'gant',
  'derimod',
  'trendyol milla',
  'trendyolmilla',
  'michael kors',
  'nine west',
  'inci',
  'eastpak',
  'bambi',
  'gap',
  'adidas',
  'nautica',
  'north face',
  'shaka',
  'diesel',
  'les benjamins',
  'kemal tanca',
  'inci',
  'reebok',
  'hummel',
  'avva',
  'hugo boss',
  'faik sonmez',
  'yargici',
  'adl',
  'aker',
  'mudo',
  'vakko',
  'sarar',
  'w collection',
  'vakkorama',
  'silk and cashmere',
  'silk cashmere',
  'chakra',
  'pierre cardin',
  'cacharel',
  'guess',
  'kigili',
  'lufian',
  'decathlon',
  'north face',
  'ds damat',
  'koton',
  'tudors',
  'puma',
  'avva',
  'skechers',
  'mango',
  'network',
  'bershka',
  'hugo boss',
  'marks&spencer',
  'marks and spencer',
  'marks spencer',
  'mavi',
  'us polo',
  'pull&bear',
  'pull and bear',
  'pull bear',
  'altinyildiz classic',
  'jack jones',
  'kigili',
  'pierre cardin',
  'tommy hilfiger',
  'lc waikiki',
  'nike',
  'adidas',
  'colins',
  'calvin klein',
  'lacoste',
  'puma',
  'levis',
  'paul&shark',
  'lumberjack',
  'giovanni gentile',
  'lee cooper',
  'columbia',
  'nautica',
  'network',
  'lee',
  'under armour',
  'hatemoglu',
  'jack wolfskin',
  'kip',
  'fabrika',
  'gant',
  'brooks brother',
  'dagi',
  'ramsey',
  'massimo dutti',
  'sarar',
  'guess',
  'armani exchange',
  'barbour',
  'benetton',
  'gap',
  'decathlon',
  'karaca',
  'vakko',
  'diesel',
  'limon company',
  'ds damat',
  'ralph lauren',
  'dolce gabbana',
  'les benjamins',
  'kemal tanca',
  'zara',
  'hummel',
  'vakko',
  'w collection',
  'vakkorama',
  'bluemint',
  'nyx',
  'avon',
  'victorias secret',
  'kiko',
  'yves rocher',
  'clinique',
  'flormar',
  'mac',
  'boyner',
  'estee lauder',
  'maybelline new york',
  'prada',
  'nivea',
  'cream co',
  'kiehls',
  'lancome',
  'versace',
  'bioderma',
  'bargello',
  'sebamed',
  'kerastase',
  'schwarzkopf',
  'sephora',
  'loreal',
  'bath and body works',
  'vichy',
  'loccitane',
  'max factor',
  'guerlain',
  'neutrogena',
  'golden rose',
  'the body shop',
  'nike',
  'puma',
  'hammer jack',
  'lumberjack',
  'jump',
  'kinetix',
  'pierre cardin',
  'us polo',
  'slazenger',
  'scooter',
  'dockers',
  'bambi',
  'vans',
  'greyder',
  'tamer tanca',
  'birkenstock',
  'new balance',
  'reebok',
  'harley davidson',
  'derimod',
  'inci',
  'timberland',
  'the north face',
  'skechers',
  'cat',
  'elle',
  'camper',
  'under armour',
  'hotic',
  'kemal tanca',
  'asics',
  'desa',
  'lacoste',
  'tommy hilfiger',
  'kappa',
  'converse',
  'lc waikiki',
  'pull&bear',
  'pull and bear',
  'pull bear',
  'guess',
  'ramsey',
  'kigili',
  'nine west',
  'ugg',
  'adidas',
  'divarese',
  'geox',
  'ecco',
  'twigy',
  'deriden',
  'guess',
  'tommy hilfiger',
  'calvin klein',
  'fossil',
  'lacoste',
  'michael kors',
  'versace',
  'puma',
  'wesse',
  'esprit',
  'emporio armani',
  'dkny',
  'swarovski',
  'casio',
  'quantum',
  'momentus',
  'prada',
  'armani exchange',
  'diesel',
  'seiko',
  'swatch',
  'nacar',
  'daniel klein',
  'quartz',
  'adidas',
  'maurice lacroix',
  'cerruti 1881',
  'gc',
  'longines',
  'bering',
  'slazenger',
  'diesel',
  'avon',
  'zara parfum',
  'bargello',
  'dior',
  'victorias secret',
  'calvin klein',
  'chanel',
  'versace',
  'burberry',
  'yves saint lauren',
  'giorgio armani',
  'gucci',
  'lnacome',
  'bvlgari',
  'dolce&gabbana',
  'tom ford',
  'estee lauder',
  'emporio armani',
  'hugo boss',
  'chloe',
  'd&p perfume',
  'axe',
  'rexona',
  'marks&spencer',
  'marks and spencer',
  'marks spencer',
  'guess',
  'prada',
  'michael kors',
  'mango perfume',
  'lacoste',
  'boss',
  'cartier',
  'gigi milano',
  'atelier rebul',
  'givenchy',
  'madame coco',
  'bella maison',
  'english home',
  'karaca',
  'emsan',
  'dogtas',
  'arzum',
  'chakra',
];

export const brandIds: Record<string, string> = {
  mango: '99',
  adidas: '83',
  nike: '105',
  puma: '337',
};

export default brands;
