import { withPalette } from '@/theme/ThemeRegistry';

const useStyles = withPalette((palette) => ({
  card: {
    p: 0,
    borderRadius: '16px',
    bgcolor: palette.white.main,
    cursor: 'pointer',
    transition: 'all 0.28s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    borderColor: palette.gray[200],
    '&:hover': {
      borderColor: palette.gray[300],
      boxShadow: '0 10px 28px rgba(17, 24, 39, 0.08)',
      transform: 'translateY(-2px)',
      '& .order-arrow': {
        transform: 'translateX(4px)',
        color: palette.text.main,
      },
    },
  },
  statusIndicator: {
    width: 5,
    alignSelf: 'stretch',
    flexShrink: 0,
    borderRadius: '0 3px 3px 0',
  },
  content: {
    flexDirection: 'row',
    alignItems: { xs: 'flex-start', lg: 'center' },
    justifyContent: 'space-between',
    flexWrap: 'nowrap',
    gap: { xs: 1, sm: 1.5, lg: 1.75 },
    px: { xs: 1.75, sm: 2.25, lg: 2.5 },
    py: { xs: 2, sm: 2.5, lg: 2.75, xl: 3 },
    width: '100%',
  },
  infoGrid: {
    flex: 1,
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, minmax(0, 1fr))',
      lg: 'minmax(160px, 1.1fr) minmax(140px, 0.95fr) minmax(180px, 1.5fr) minmax(110px, 0.8fr)',
    },
    gap: { xs: 0.75, sm: 1, lg: 1.1 },
  },
  infoCell: {
    p: 0,
    borderRadius: 0,
    bgcolor: 'transparent',
    border: 'none',
    minWidth: 0,
  },
  orderIdLabel: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.2,
    color: palette.text.medium,
    lineHeight: 1.2,
  },
  orderId: {
    fontSize: { xs: 16, sm: 17 },
    fontWeight: 700,
    color: palette.text.main,
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  metaLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.45,
    color: palette.text.medium,
    lineHeight: 1.2,
  },
  metaValue: {
    fontSize: { xs: 13, sm: 14 },
    fontWeight: 500,
    color: palette.text.mediumLight,
    lineHeight: 1.4,
  },
  metaValueEllipsis: {
    fontSize: { xs: 13, sm: 14 },
    fontWeight: 500,
    color: palette.text.mediumLight,
    lineHeight: 1.4,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  totalValue: {
    fontSize: { xs: 15, sm: 16 },
    fontWeight: 700,
    color: palette.text.main,
    lineHeight: 1.3,
  },
  statusChip: {
    height: 32,
    borderRadius: '10px',
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: 0.25,
    textTransform: 'uppercase' as const,
    minWidth: { xs: 112, sm: 118, lg: 126 },
    maxWidth: { xs: 118, sm: 130, lg: 140 },
  },
  actionArea: {
    minWidth: { xs: 0, lg: 128, xl: 146 },
    width: { xs: 'auto', md: 'auto' },
    justifyContent: 'flex-end',
    flexShrink: 0,
    borderLeft: 'none',
    pl: { xs: 0, lg: 0.25, xl: 0.5 },
    alignSelf: 'stretch',
  },
  arrowContainer: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '999px',
    bgcolor: '#F7F8FA',
    color: palette.text.disabled,
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    flexShrink: 0,
    display: { xs: 'none', xl: 'flex' },
  },
}));

export default useStyles;
