const styles = {
  page: {
    px: { xs: 1.5, md: 4 },
    py: { xs: 2, md: 4 },
    alignItems: 'center',
    bgcolor: '#FBFBFA',
    minHeight: { xs: 'calc(100vh - 88px)', md: 'calc(100vh - 112px)' },
  },
  container: {
    width: '100%',
    maxWidth: 980,
    gap: 2,
    minWidth: 0,
  },
  title: {
    fontSize: { xs: 30, sm: 36, md: 40 },
    lineHeight: 1.08,
    fontWeight: 850,
    letterSpacing: 0,
    color: '#101820',
    maxWidth: 420,
  },
  description: {
    color: '#5F6670',
    maxWidth: 400,
    lineHeight: 1.6,
    fontSize: { xs: 14.5, md: 15 },
  },
  loadingCard: {
    p: 4,
    minHeight: 280,
    display: 'grid',
    placeItems: 'center',
    borderRadius: '20px',
    border: '1px solid #E9E5DD',
    boxShadow: '0 22px 60px rgba(16, 24, 32, 0.06)',
  },
  lookupShell: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'minmax(0, 0.95fr) minmax(340px, 0.82fr)' },
    gap: { xs: 2, md: 3 },
    alignItems: 'center',
  },
  lookupIntro: {
    gap: 1,
  },
  lookupCard: {
    p: { xs: 2, sm: 2.5, md: 3 },
    borderRadius: '18px',
    border: 'none',
    boxShadow: '0 16px 42px rgba(16, 24, 32, 0.055)',
    bgcolor: '#FFFFFF',
    '& .MuiOutlinedInput-root': {
      borderRadius: '12px',
      bgcolor: '#FFFFFF',
    },
  },
  formPanel: {
    width: '100%',
    p: 0,
    borderRadius: { xs: 0, md: '18px' },
    bgcolor: 'transparent',
  },
  lookupTitle: {
    fontSize: 18,
    fontWeight: 850,
    color: '#101820',
  },
  lookupDescription: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 1.55,
  },
  accountPrompt: {
    mt: 0.25,
    pt: 1.25,
    borderTop: '1px solid #EEEAE3',
    gap: 0.5,
  },
  accountPromptText: {
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 1.5,
  },
  resultLayout: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'minmax(0, 1.5fr) minmax(320px, 0.8fr)' },
    gap: 2,
    alignItems: 'start',
    minWidth: 0,
  },
  statusCard: {
    p: { xs: 1.5, md: 3 },
    minWidth: 0,
    overflow: 'hidden',
    borderRadius: { xs: '18px', md: '24px' },
    border: '1px solid #E9E5DD',
    boxShadow: '0 24px 70px rgba(16, 24, 32, 0.08)',
  },
  statusHeader: {
    flexDirection: { xs: 'column', sm: 'row' },
    gap: 1.5,
    justifyContent: 'space-between',
  },
  statusIconBox: (bg: string, color: string) => ({
    width: { xs: 42, md: 52 },
    height: { xs: 42, md: 52 },
    flex: '0 0 auto',
    borderRadius: { xs: '14px', md: '18px' },
    display: 'grid',
    placeItems: 'center',
    bgcolor: bg,
    color,
  }),
  mutedLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: 700,
  },
  statusTitle: (color: string) => ({
    fontWeight: 850,
    fontSize: { xs: 19, md: 24 },
    color,
    overflowWrap: 'anywhere',
  }),
  orderPill: {
    alignSelf: { xs: 'flex-start', sm: 'center' },
    px: 1.3,
    py: 0.75,
    borderRadius: '999px',
    bgcolor: '#F2EFE8',
    color: '#4B5563',
    fontSize: 12,
    fontWeight: 800,
    maxWidth: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  deliveryPanel: {
    gap: 1.25,
    p: { xs: 1.2, md: 1.75 },
    borderRadius: { xs: '14px', md: '18px' },
    bgcolor: '#F8FAF7',
    border: '1px solid #E1EBDC',
  },
  deliveryIconBox: {
    width: 36,
    height: 36,
    borderRadius: '12px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: '#FFFFFF',
    color: '#333942',
    border: '1px solid #E1EBDC',
  },
  deliveryTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: '#101820',
  },
  deliveryText: {
    color: '#5F6873',
    fontSize: 13,
    lineHeight: 1.55,
  },
  timeline: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: { xs: 0.25, sm: 0.75 },
    py: { xs: 0.25, md: 0.75 },
    overflow: 'hidden',
  },
  timelineDot: (isDone: boolean, color: string) => ({
    width: 12,
    height: 12,
    borderRadius: '50%',
    bgcolor: isDone ? color : '#D9D6D0',
    boxShadow: isDone ? `0 0 0 5px ${color}1A` : 'none',
  }),
  timelineLabel: (isDone: boolean) => ({
    fontSize: { xs: 9.5, sm: 12 },
    color: isDone ? '#111827' : '#777E87',
    fontWeight: isDone ? 800 : 650,
    whiteSpace: { xs: 'normal', sm: 'nowrap' },
    textAlign: 'center',
    lineHeight: 1.15,
  }),
  timelineLine: (isDone: boolean, color: string) => ({
    height: 2,
    minWidth: 0,
    flex: 1,
    mx: { xs: 0.1, sm: 0.4 },
    bgcolor: isDone ? color : '#E5E0D8',
    transform: 'translateY(-12px)',
  }),
  infoGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    columnGap: { xs: 2, sm: 3 },
    rowGap: 0.75,
  },
  infoCard: {
    p: 0,
    border: 'none',
    borderRadius: 0,
    bgcolor: 'transparent',
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 0.75,
  },
  infoLabel: {
    color: '#777E87',
    fontSize: 13,
  },
  infoValue: (strong: boolean) => ({
    fontWeight: strong ? 800 : 700,
    fontSize: 14,
    color: '#101820',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  }),
  sectionTitle: {
    fontWeight: 850,
    color: '#101820',
  },
  productRow: {
    minHeight: 48,
    p: 0.75,
    borderRadius: '14px',
    bgcolor: '#FCFBF8',
    border: '1px solid #EEEAE3',
    minWidth: 0,
  },
  productThumb: {
    width: 36,
    height: 36,
    flex: '0 0 auto',
    borderRadius: '10px',
    overflow: 'hidden',
    display: 'grid',
    placeItems: 'center',
    bgcolor: '#F3F2EF',
    color: '#333942',
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      display: 'block',
    },
  },
  productName: {
    color: '#4F565F',
    fontSize: 14,
    flex: 1,
    minWidth: 0,
    overflowWrap: 'anywhere',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    lineHeight: 1.35,
  },
  productQuantity: {
    fontWeight: 800,
    fontSize: 14,
    color: '#101820',
    whiteSpace: 'nowrap',
  },
  detailCard: {
    p: { xs: 1.75, md: 2.25 },
    bgcolor: '#FFFFFF',
    color: '#101820',
    borderRadius: '16px',
    border: '1px solid #E9E5DD',
    boxShadow: '0 16px 42px rgba(16, 24, 32, 0.055)',
  },
  lockIconBox: {
    width: 38,
    height: 38,
    flex: '0 0 auto',
    borderRadius: '12px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: '#F5F3EF',
    border: '1px solid #E9E5DD',
    color: '#333942',
  },
  detailTitle: {
    fontWeight: 850,
    fontSize: 16,
  },
  detailDescription: {
    color: '#626B75',
    lineHeight: 1.6,
    fontSize: 14,
  },
  unlockList: {
    gap: 0.65,
    '& p': {
      color: '#4F565F',
      fontSize: 13,
      fontWeight: 700,
      '&:before': {
        content: '"+"',
        display: 'inline-block',
        mr: 1,
        color: '#8B8377',
        fontWeight: 900,
      },
    },
  },
  errorText: {
    color: 'error.main',
    fontSize: 13,
    fontWeight: 700,
  },
};

export default styles;
